import type { Analysis, Verdict } from "@/lib/analysis"
import RAW from "@/lib/data/analysis.json"

/**
 * The analysis results, keyed by component id.
 *
 * Generated by `npm run analyse` from each component's own source, so a badge
 * always corresponds to something in the code.
 */
export const ANALYSIS = RAW as unknown as Record<string, Analysis>

export type CheckId = "themeable" | "reducedMotion" | "focusVisible"

export const CHECKS: {
  id: CheckId
  label: string
  /** what a pass means, in the user's terms */
  passes: string
  fails: string
}[] = [
  {
    id: "themeable",
    label: "Themeable",
    passes: "Uses design tokens, so it takes on your theme",
    fails: "Hard-codes its colours and won't follow your theme",
  },
  {
    id: "reducedMotion",
    label: "Reduced motion",
    passes: "Honours prefers-reduced-motion, or doesn't animate",
    fails: "Animates regardless of the reduced-motion setting",
  },
  {
    id: "focusVisible",
    label: "Focus visible",
    passes: "Interactive elements keep a visible focus indicator",
    fails: "Removes the focus indicator without replacing it",
  },
]

export function getAnalysis(componentId: string): Analysis | null {
  return ANALYSIS[componentId] ?? null
}

/** Components that pass every check we can decide. */
export function passesAll(componentId: string): boolean {
  const analysis = getAnalysis(componentId)
  if (!analysis) return false
  return CHECKS.every(({ id }) => analysis[id] === "pass" || analysis[id] === "unknown")
}

export function matchesQuality(componentId: string, required: CheckId[]): boolean {
  if (required.length === 0) return true
  const analysis = getAnalysis(componentId)
  if (!analysis) return false
  // "unknown" doesn't satisfy a filter — the user asked for a guarantee
  return required.every((id) => analysis[id] === "pass")
}

export const VERDICT_LABEL: Record<Verdict, string> = {
  pass: "Pass",
  partial: "Partial",
  fail: "Fail",
  unknown: "Not applicable",
}
