import dynamic from "next/dynamic"
import { IMPORTED_REGISTRY } from "./imported"
import type { ComponentType } from "react"

/**
 * Every publishable component in the registry maps a `previewKey` to its demo.
 * Demos are loaded lazily so a grid of previews doesn't ship every bundle at once.
 */
export const REGISTRY: Record<string, ComponentType> = {
  "swipe-deck": dynamic(() => import("./demos/swipe-deck")),
  "radial-carousel": dynamic(() => import("./demos/radial-carousel")),
  "snap-rail": dynamic(() => import("./demos/snap-rail")),
  "waitlist-form": dynamic(() => import("./demos/waitlist-form")),
  "auto-tabs": dynamic(() => import("./demos/auto-tabs")),
  "trail-cursor": dynamic(() => import("./demos/trail-cursor")),
  "gooey-nav": dynamic(() => import("./demos/gooey-nav")),
  "pin-stack": dynamic(() => import("./demos/pin-stack")),
  "repel-grid": dynamic(() => import("./demos/repel-grid")),
  "image-accordion": dynamic(() => import("./demos/image-accordion")),
  "velocity-marquee": dynamic(() => import("./demos/velocity-marquee")),
  "terminal-cast": dynamic(() => import("./demos/terminal-cast")),
  "depth-marquee": dynamic(() => import("./demos/depth-marquee")),
  "unfold-hero": dynamic(() => import("./demos/unfold-hero")),
  "spin-cube": dynamic(() => import("./demos/spin-cube")),
  "layer-stack-3d": dynamic(() => import("./demos/layer-stack-3d")),
  "extruded-text": dynamic(() => import("./demos/extruded-text")),
  "closing-cta": dynamic(() => import("./demos/closing-cta")),
  "compare-table": dynamic(() => import("./demos/compare-table")),
  "scroll-spotlight": dynamic(() => import("./demos/scroll-spotlight")),
  "async-button": dynamic(() => import("./demos/async-button")),
  "keycap-button": dynamic(() => import("./demos/keycap-button")),
  "ticket-button": dynamic(() => import("./demos/ticket-button")),
  "halo-button": dynamic(() => import("./demos/halo-button")),
  "split-flap": dynamic(() => import("./demos/split-flap")),
  "drag-board": dynamic(() => import("./demos/drag-board")),
  "trend-chart": dynamic(() => import("./demos/trend-chart")),
  "waveform-scrubber": dynamic(() => import("./demos/waveform-scrubber")),
  "dither-image": dynamic(() => import("./demos/dither-image")),
  "usage-calculator": dynamic(() => import("./demos/usage-calculator")),
  "logo-cloud": dynamic(() => import("./demos/logo-cloud")),
  "orbit-gallery": dynamic(() => import("./demos/orbit-gallery")),
  "operator-bento": dynamic(() => import("./demos/operator-bento")),
  "lens-flare": dynamic(() => import("./demos/lens-flare")),
  "flip-switch-slider": dynamic(() => import("./demos/flip-switch-slider")),
  "editorial-coverflow": dynamic(() => import("./demos/editorial-coverflow")),
  "filmstrip-hero": dynamic(() => import("./demos/filmstrip-hero")),
  "frost-reveal": dynamic(() => import("./demos/frost-reveal")),
  "stroke-draw-hero": dynamic(() => import("./demos/stroke-draw-hero")),
  "animated-hero": dynamic(() => import("./demos/animated-hero")),
  "coverflow-carousel": dynamic(() => import("./demos/coverflow-carousel")),
  "hover-reveal-list": dynamic(() => import("./demos/hover-reveal-list")),
  "convergence-field": dynamic(() => import("./demos/convergence-field")),
  "type-portal": dynamic(() => import("./demos/type-portal")),
  "liquid-metal-button": dynamic(() => import("./demos/liquid-metal-button")),
  "thumbnail-carousel": dynamic(() => import("./demos/thumbnail-carousel")),
  "marquee-hero": dynamic(() => import("./demos/marquee-hero")),
  "integration-web": dynamic(() => import("./demos/integration-web")),
  "stack-spread": dynamic(() => import("./demos/stack-spread")),
  "animated-grid": dynamic(() => import("./demos/animated-grid")),
  "gradient-orbs": dynamic(() => import("./demos/gradient-orbs")),
  "wavy-lines": dynamic(() => import("./demos/wavy-lines")),
  "ripple-pulse": dynamic(() => import("./demos/ripple-pulse")),
  "noise-gradient": dynamic(() => import("./demos/noise-gradient")),
  "starfield": dynamic(() => import("./demos/starfield")),
  "beam-sweep": dynamic(() => import("./demos/beam-sweep")),
  "topographic": dynamic(() => import("./demos/topographic")),
  "diagonal-stripes": dynamic(() => import("./demos/diagonal-stripes")),
  "aurora-background": dynamic(() => import("./demos/aurora-background")),
  "shimmer-button": dynamic(() => import("./demos/shimmer-button")),
  "gradient-button": dynamic(() => import("./demos/gradient-button")),
  "liquid-glass-button": dynamic(() => import("./demos/liquid-glass-button")),
  "number-ticker": dynamic(() => import("./demos/number-ticker")),
  "text-shimmer": dynamic(() => import("./demos/text-shimmer")),
  "bento-grid": dynamic(() => import("./demos/bento-grid")),
  "pricing-section": dynamic(() => import("./demos/pricing-section")),
  marquee: dynamic(() => import("./demos/marquee")),
  "testimonials-columns": dynamic(() => import("./demos/testimonials-columns")),
  "faq-accordion": dynamic(() => import("./demos/faq-accordion")),
  "sign-in-card": dynamic(() => import("./demos/sign-in-card")),
  "ai-chat-input": dynamic(() => import("./demos/ai-chat-input")),
  "typewriter-text": dynamic(() => import("./demos/typewriter-text")),
  "spotlight-card": dynamic(() => import("./demos/spotlight-card")),
  "dot-pattern": dynamic(() => import("./demos/dot-pattern")),
  "macos-dock": dynamic(() => import("./demos/macos-dock")),
  "kpi-card": dynamic(() => import("./demos/kpi-card")),
  "file-tree": dynamic(() => import("./demos/file-tree")),
  "animated-tabs": dynamic(() => import("./demos/animated-tabs")),
  "avatar-stack": dynamic(() => import("./demos/avatar-stack")),
  "notification-list": dynamic(() => import("./demos/notification-list")),
  timeline: dynamic(() => import("./demos/timeline")),
  "mesh-gradient": dynamic(() => import("./demos/mesh-gradient")),
  "tilt-card": dynamic(() => import("./demos/tilt-card")),
  "progress-ring": dynamic(() => import("./demos/progress-ring")),
  "footer-section": dynamic(() => import("./demos/footer-section")),
  "stats-section": dynamic(() => import("./demos/stats-section")),
  "empty-state": dynamic(() => import("./demos/empty-state")),
  "status-badge": dynamic(() => import("./demos/status-badge")),
  "data-table": dynamic(() => import("./demos/data-table")),
  "command-palette": dynamic(() => import("./demos/command-palette")),
  "plasma-shader": dynamic(() => import("./demos/plasma-shader")),
  "wave-lines": dynamic(() => import("./demos/wave-lines")),
  "grain-overlay": dynamic(() => import("./demos/grain-overlay")),
  "image-comparison": dynamic(() => import("./demos/image-comparison")),
  "feature-steps": dynamic(() => import("./demos/feature-steps")),
  "toast-stack": dynamic(() => import("./demos/toast-stack")),
  "mini-calendar": dynamic(() => import("./demos/mini-calendar")),
  "collapsible-sidebar": dynamic(() => import("./demos/collapsible-sidebar")),
  "scroll-reveal-text": dynamic(() => import("./demos/scroll-reveal-text")),
  "team-grid": dynamic(() => import("./demos/team-grid")),
  "glow-card": dynamic(() => import("./demos/glow-card")),

  // navigation, chrome, carousels and motion
  "sticky-navbar": dynamic(() => import("./demos/sticky-navbar")),
  "mega-menu": dynamic(() => import("./demos/mega-menu")),
  "image-carousel": dynamic(() => import("./demos/image-carousel")),
  "testimonial-spotlight": dynamic(() => import("./demos/testimonial-spotlight")),
  "reading-progress": dynamic(() => import("./demos/reading-progress")),
  "text-scramble": dynamic(() => import("./demos/text-scramble")),
  "magnetic-button": dynamic(() => import("./demos/magnetic-button")),
  "particle-field": dynamic(() => import("./demos/particle-field")),
  "editor-toolbar": dynamic(() => import("./demos/editor-toolbar")),
  "mega-footer": dynamic(() => import("./demos/mega-footer")),
  "sidebar-rail": dynamic(() => import("./demos/sidebar-rail")),
}

/** Full-page templates, previewed the same way components are. */
export const TEMPLATE_REGISTRY: Record<string, ComponentType> = {
  "saas-landing": dynamic(() => import("./templates/saas-landing")),
  "agent-scheduler": dynamic(() => import("./templates/agent-scheduler")),
  "ai-platform": dynamic(() => import("./templates/ai-platform")),
  "status-page": dynamic(() => import("./templates/status-page")),
  "support-desk": dynamic(() => import("./templates/support-desk")),
  "conference": dynamic(() => import("./templates/conference")),
  "analytics-dashboard": dynamic(() => import("./templates/analytics-dashboard")),
  waitlist: dynamic(() => import("./templates/waitlist")),
  agency: dynamic(() => import("./templates/agency")),
  "docs-portal": dynamic(() => import("./templates/docs-portal")),
  changelog: dynamic(() => import("./templates/changelog")),
  portfolio: dynamic(() => import("./templates/portfolio")),
  "ai-product": dynamic(() => import("./templates/ai-product")),
  ecommerce: dynamic(() => import("./templates/ecommerce")),
}

export const ALL_PREVIEWS: Record<string, ComponentType> = {
  ...REGISTRY,
  ...IMPORTED_REGISTRY,
  ...TEMPLATE_REGISTRY,
}

export const REGISTRY_KEYS = Object.keys({ ...REGISTRY, ...IMPORTED_REGISTRY })
