#!/usr/bin/env node
/**
 * Builds the open-source apps directory from the GitHub API.
 *
 * Every entry is a real repository, verified at fetch time, with its own
 * description and star count rather than a hand-copied blurb. Re-run with
 * `npm run apps:fetch` to refresh the numbers.
 *
 * Unauthenticated GitHub allows 60 requests an hour, which covers this list.
 * Set GITHUB_TOKEN to raise it if the list grows.
 */
import { writeFileSync } from "node:fs"

const OUT = "src/lib/data/apps.ts"

/** repo → the category it belongs in on our page */
const CANDIDATES = {
  "calcom/cal.com": "business",
  "documenso/documenso": "business",
  "twentyhq/twenty": "business",
  "makeplane/plane": "business",
  "formbricks/formbricks": "business",
  "dubinc/dub": "business",
  "unkeyed/unkey": "devtools",
  "openstatusHQ/openstatus": "devtools",
  "triggerdotdev/trigger.dev": "devtools",
  "infisical/infisical": "devtools",
  "novuhq/novu": "devtools",
  "typebot-io/typebot": "business",
  "medusajs/medusa": "commerce",
  "vercel/commerce": "commerce",
  "payloadcms/payload": "cms",
  "strapi/strapi": "cms",
  "directus/directus": "cms",
  "keystonejs/keystone": "cms",
  "nocodb/nocodb": "data",
  "teableio/teable": "data",
  "windmill-labs/windmill": "devtools",
  "activepieces/activepieces": "devtools",
  "n8n-io/n8n": "devtools",
  "appsmithorg/appsmith": "devtools",
  "refinedev/refine": "devtools",
  "steven-tey/novel": "personal",
  "typehero/typehero": "personal",
  "lukevella/rallly": "personal",
  "ghostfolio/ghostfolio": "personal",
  "mfts/papermark": "business",
  "elie222/inbox-zero": "personal",
  "midday-ai/midday": "business",
  "Dokploy/dokploy": "devtools",
  "lobehub/lobe-chat": "ai",
  "danny-avila/LibreChat": "ai",
  "open-webui/open-webui": "ai",
  "mckaywrigley/chatbot-ui": "ai",
  "tolgee/tolgee-platform": "devtools",
  "BuilderIO/builder": "cms",
  "vercel/platforms": "devtools",
}

const headers = {
  accept: "application/vnd.github+json",
  "user-agent": "NuxusAppsDirectory/1.0",
  ...(process.env.GITHUB_TOKEN ? { authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
}

const apps = []
const missing = []

for (const [repo, category] of Object.entries(CANDIDATES)) {
  try {
    const response = await fetch(`https://api.github.com/repos/${repo}`, {
      headers,
      signal: AbortSignal.timeout(15000),
    })

    if (!response.ok) {
      missing.push(`${repo} (${response.status})`)
      continue
    }

    const data = await response.json()

    apps.push({
      slug: repo.split("/")[1].toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      name: data.name,
      owner: data.owner.login,
      repo,
      description: (data.description ?? "").trim(),
      homepage: data.homepage || null,
      stars: data.stargazers_count,
      language: data.language ?? null,
      license: data.license?.spdx_id ?? null,
      topics: (data.topics ?? []).slice(0, 6),
      category,
      updatedAt: data.pushed_at,
    })
  } catch (error) {
    missing.push(`${repo} (${error instanceof Error ? error.message : "failed"})`)
  }
}

apps.sort((a, b) => b.stars - a.stars)

const file = `// Generated by scripts/fetch-apps.mjs — do not edit by hand.
// Every entry is a real public repository, verified against the GitHub API.
// Snapshot taken: ${new Date().toISOString()}

export interface OpenSourceApp {
  slug: string
  name: string
  owner: string
  /** "owner/name" */
  repo: string
  description: string
  homepage: string | null
  stars: number
  language: string | null
  /** SPDX identifier, e.g. "MIT" */
  license: string | null
  topics: string[]
  category: AppCategory
  /** last push, ISO */
  updatedAt: string
}

export type AppCategory = "business" | "devtools" | "ai" | "cms" | "commerce" | "data" | "personal"

export const APP_CATEGORIES: { id: AppCategory; label: string }[] = [
  { id: "business", label: "Business & SaaS" },
  { id: "devtools", label: "Developer tools" },
  { id: "ai", label: "AI" },
  { id: "cms", label: "CMS & content" },
  { id: "commerce", label: "Commerce" },
  { id: "data", label: "Data" },
  { id: "personal", label: "Personal" },
]

export const APPS_SNAPSHOT_AT = "${new Date().toISOString()}"

export const APPS: OpenSourceApp[] = ${JSON.stringify(apps, null, 2)}
`

writeFileSync(OUT, file)

console.log(`[apps] ${apps.length} repositories written to ${OUT}`)
if (missing.length) console.log(`[apps] skipped ${missing.length}: ${missing.join(", ")}`)
