// Generated by scripts/fetch-apps.mjs — do not edit by hand.
// Every entry is a real public repository, verified against the GitHub API.
// Snapshot taken: 2026-09-11T21:26:43.070Z

export interface OpenSourceApp {
  slug: string
  name: string
  owner: string
  /** "owner/name" */
  repo: string
  description: string
  homepage: string | null
  stars: number
  language: string | null
  /** SPDX identifier, e.g. "MIT" */
  license: string | null
  topics: string[]
  category: AppCategory
  /** last push, ISO */
  updatedAt: string
}

export type AppCategory = "business" | "devtools" | "ai" | "cms" | "commerce" | "data" | "personal"

export const APP_CATEGORIES: { id: AppCategory; label: string }[] = [
  { id: "business", label: "Business & SaaS" },
  { id: "devtools", label: "Developer tools" },
  { id: "ai", label: "AI" },
  { id: "cms", label: "CMS & content" },
  { id: "commerce", label: "Commerce" },
  { id: "data", label: "Data" },
  { id: "personal", label: "Personal" },
]

export const APPS_SNAPSHOT_AT = "2026-09-11T21:26:43.076Z"

export const APPS: OpenSourceApp[] = [
  {
    "slug": "n8n",
    "name": "n8n",
    "owner": "n8n-io",
    "repo": "n8n-io/n8n",
    "description": "Fair-code workflow automation platform with native AI capabilities. Combine visual building with custom code, self-host or cloud, 400+ integrations.",
    "homepage": "https://n8n.io",
    "stars": 204033,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "ai",
      "apis",
      "automation",
      "cli",
      "data-flow",
      "development"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T21:17:41Z"
  },
  {
    "slug": "open-webui",
    "name": "open-webui",
    "owner": "open-webui",
    "repo": "open-webui/open-webui",
    "description": "User-friendly AI Interface (Supports Ollama, OpenAI API, ...)",
    "homepage": "https://openwebui.com",
    "stars": 151668,
    "language": "Python",
    "license": "NOASSERTION",
    "topics": [
      "ai",
      "llm",
      "llm-ui",
      "llm-webui",
      "llms",
      "mcp"
    ],
    "category": "ai",
    "updatedAt": "2026-09-10T23:05:38Z"
  },
  {
    "slug": "lobe-chat",
    "name": "lobehub",
    "owner": "lobehub",
    "repo": "lobehub/lobe-chat",
    "description": "🤯 LobeHub is your Chief Agent Operator, organizing your agents into 7×24 operations by hiring, scheduling, and reporting on your entire AI team.",
    "homepage": "https://lobehub.com",
    "stars": 82408,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "agent",
      "agent-collaboration",
      "agent-harness",
      "ai",
      "cao",
      "chatgpt"
    ],
    "category": "ai",
    "updatedAt": "2026-09-11T20:24:31Z"
  },
  {
    "slug": "strapi",
    "name": "strapi",
    "owner": "strapi",
    "repo": "strapi/strapi",
    "description": "🚀 Strapi is the leading open-source headless CMS. It’s 100% JavaScript/TypeScript, fully customizable, and developer-first.",
    "homepage": "https://strapi.io",
    "stars": 73127,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "api",
      "cms",
      "cms-framework",
      "content-management",
      "content-management-system",
      "customizable"
    ],
    "category": "cms",
    "updatedAt": "2026-09-11T20:51:12Z"
  },
  {
    "slug": "nocodb",
    "name": "nocodb",
    "owner": "nocodb",
    "repo": "nocodb/nocodb",
    "description": "🔥 🔥 🔥 A Free & Self-hostable Airtable Alternative",
    "homepage": "https://nocodb.com",
    "stars": 64932,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "airtable",
      "airtable-alternative",
      "automatic-api",
      "hacktoberfest",
      "low-code",
      "no-code"
    ],
    "category": "data",
    "updatedAt": "2026-09-11T18:50:22Z"
  },
  {
    "slug": "plane",
    "name": "plane",
    "owner": "makeplane",
    "repo": "makeplane/plane",
    "description": "🔥🔥🔥 Open-source Jira, Linear, Monday, and ClickUp alternative. Plane is a modern project management platform to manage tasks, sprints, docs, and triage.",
    "homepage": "http://plane.so",
    "stars": 59243,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "boards",
      "bug-tracker",
      "django",
      "docker",
      "gantt",
      "issue-tracker"
    ],
    "category": "business",
    "updatedAt": "2026-09-11T07:07:43Z"
  },
  {
    "slug": "twenty",
    "name": "twenty",
    "owner": "twentyhq",
    "repo": "twentyhq/twenty",
    "description": "The open alternative to Salesforce, designed for AI.",
    "homepage": "https://twenty.com",
    "stars": 56612,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "crm",
      "crm-system",
      "customer",
      "good-first-issue",
      "graphql",
      "hacktoberfest"
    ],
    "category": "business",
    "updatedAt": "2026-09-11T20:17:47Z"
  },
  {
    "slug": "cal-com",
    "name": "cal.diy",
    "owner": "calcom",
    "repo": "calcom/cal.com",
    "description": "Scheduling infrastructure for absolutely everyone.",
    "homepage": "https://cal.diy",
    "stars": 48384,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "next-auth",
      "nextjs",
      "open-source",
      "postgresql",
      "prisma",
      "t3-stack"
    ],
    "category": "business",
    "updatedAt": "2026-09-09T19:27:35Z"
  },
  {
    "slug": "payload",
    "name": "payload",
    "owner": "payloadcms",
    "repo": "payloadcms/payload",
    "description": "Payload is the open-source, fullstack Next.js framework, giving you instant backend superpowers. Get a full TypeScript backend and admin panel instantly. Use Payload as a headless CMS or for building powerful applications.",
    "homepage": "https://payloadcms.com",
    "stars": 44695,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "cms",
      "content-management",
      "content-management-system",
      "express",
      "graphql",
      "headless"
    ],
    "category": "cms",
    "updatedAt": "2026-09-11T20:01:52Z"
  },
  {
    "slug": "librechat",
    "name": "LibreChat",
    "owner": "danny-avila",
    "repo": "danny-avila/LibreChat",
    "description": "Enhanced ChatGPT Clone: Features Agents, MCP, Skills, DeepSeek, Anthropic, AWS, OpenAI, Responses API, Azure, Groq, o1, GPT-5, Mistral, OpenRouter, Vertex AI, Gemini, Artifacts, AI model switching, message search, Code Interpreter, langchain, DALL-E-3, OpenAPI Actions, Functions, Secure Multi-User Auth, Presets, open-source for self-hosting. Active",
    "homepage": "https://librechat.ai/",
    "stars": 43043,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "ai",
      "anthropic",
      "artifacts",
      "aws",
      "azure",
      "chatgpt"
    ],
    "category": "ai",
    "updatedAt": "2026-09-11T21:26:20Z"
  },
  {
    "slug": "appsmith",
    "name": "appsmith",
    "owner": "appsmithorg",
    "repo": "appsmithorg/appsmith",
    "description": "Platform to build admin panels, internal tools, and dashboards. Integrates with 25+ databases and any API.",
    "homepage": "https://www.appsmith.com",
    "stars": 40861,
    "language": "TypeScript",
    "license": "Apache-2.0",
    "topics": [
      "admin-dashboard",
      "admin-panels",
      "app-builder",
      "automation",
      "crud",
      "custom-internal"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T15:49:28Z"
  },
  {
    "slug": "novu",
    "name": "novu",
    "owner": "novuhq",
    "repo": "novuhq/novu",
    "description": "The open-source communication infrastructure for agents and products",
    "homepage": "https://go.novu.co/github",
    "stars": 39969,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "agents",
      "communication",
      "email",
      "inbox",
      "infrastructure",
      "nodejs"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T17:40:04Z"
  },
  {
    "slug": "directus",
    "name": "directus",
    "owner": "directus",
    "repo": "directus/directus",
    "description": "The flexible backend for all your projects 🐰 Turn your DB into a headless CMS, admin panels, or apps with a custom UI, instant APIs, auth & more.",
    "homepage": "https://directus.com",
    "stars": 37869,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "api",
      "app",
      "cms",
      "composable",
      "data-visualization",
      "database"
    ],
    "category": "cms",
    "updatedAt": "2026-09-11T20:59:46Z"
  },
  {
    "slug": "dokploy",
    "name": "dokploy",
    "owner": "Dokploy",
    "repo": "Dokploy/dokploy",
    "description": "Open Source Alternative to Vercel, Netlify and Heroku.",
    "homepage": "https://dokploy.com/",
    "stars": 37240,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "agents",
      "ai",
      "backend",
      "backups",
      "databases",
      "deployment"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T08:20:23Z"
  },
  {
    "slug": "medusa",
    "name": "medusa",
    "owner": "medusajs",
    "repo": "medusajs/medusa",
    "description": "The world's most flexible commerce platform for agents and developers",
    "homepage": "https://medusajs.com",
    "stars": 36256,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "ai-coding",
      "ai-tools",
      "commerce",
      "e-commerce",
      "ecommerce",
      "framework"
    ],
    "category": "commerce",
    "updatedAt": "2026-09-11T21:17:59Z"
  },
  {
    "slug": "refine",
    "name": "refine",
    "owner": "refinedev",
    "repo": "refinedev/refine",
    "description": "A React Framework for building  internal tools, admin panels, dashboards & B2B apps with unmatched flexibility.",
    "homepage": "https://refine.dev",
    "stars": 35662,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "admin",
      "admin-ui",
      "ant-design",
      "crud",
      "developer-tools",
      "frontend-framework"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-10T12:56:35Z"
  },
  {
    "slug": "chatbot-ui",
    "name": "chatbot-ui",
    "owner": "mckaywrigley",
    "repo": "mckaywrigley/chatbot-ui",
    "description": "AI chat for any model.",
    "homepage": "https://JoinTakeoff.com",
    "stars": 33350,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [],
    "category": "ai",
    "updatedAt": "2024-08-03T00:38:07Z"
  },
  {
    "slug": "infisical",
    "name": "infisical",
    "owner": "Infisical",
    "repo": "infisical/infisical",
    "description": "Infisical is the open-source platform for secrets, certificates, and privileged access management.",
    "homepage": "https://infisical.com",
    "stars": 29217,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "acme",
      "certificate-management",
      "cli",
      "environment-variables",
      "go",
      "golang"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T21:23:31Z"
  },
  {
    "slug": "dub",
    "name": "dub",
    "owner": "dubinc",
    "repo": "dubinc/dub",
    "description": "The modern link attribution platform. Loved by world-class marketing teams like Framer, Perplexity, Superhuman, Twilio, Buffer and more.",
    "homepage": "https://dub.co",
    "stars": 24725,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "clickhouse",
      "mysql",
      "nextjs",
      "open-source",
      "planetscale",
      "prisma"
    ],
    "category": "business",
    "updatedAt": "2026-09-11T21:16:43Z"
  },
  {
    "slug": "activepieces",
    "name": "activepieces",
    "owner": "activepieces",
    "repo": "activepieces/activepieces",
    "description": "AI Agents & MCPs & AI Workflow Automation • (~400 MCP servers for AI agents) • AI Automation / AI Agent with MCPs • AI Workflows & AI Agents • MCPs for AI Agents",
    "homepage": "https://www.activepieces.com",
    "stars": 24408,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "ai-agent",
      "ai-agent-tools",
      "ai-agents",
      "ai-agents-framework",
      "mcp",
      "mcp-server"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T21:21:09Z"
  },
  {
    "slug": "teable",
    "name": "teable",
    "owner": "teableio",
    "repo": "teableio/teable",
    "description": "✨ AI Spreadsheet for Business",
    "homepage": "https://teable.ai",
    "stars": 21768,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "ai-agent",
      "airtable",
      "airtable-alternative",
      "app-builder",
      "database",
      "internal-tool"
    ],
    "category": "data",
    "updatedAt": "2026-09-11T08:55:43Z"
  },
  {
    "slug": "windmill",
    "name": "windmill",
    "owner": "windmill-labs",
    "repo": "windmill-labs/windmill",
    "description": "Open-source developer platform to power your entire infra and turn scripts into webhooks, workflows and UIs. Fastest workflow engine (13x vs Airflow). Open-source alternative to Retool and Temporal.",
    "homepage": "https://windmill.dev",
    "stars": 17886,
    "language": "Rust",
    "license": "NOASSERTION",
    "topics": [
      "low-code",
      "open-source",
      "platform",
      "postgresql",
      "python",
      "self-hostable"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T19:42:00Z"
  },
  {
    "slug": "novel",
    "name": "novel",
    "owner": "steven-tey",
    "repo": "steven-tey/novel",
    "description": "Notion-style WYSIWYG editor with AI-powered autocompletion.",
    "homepage": "https://novel.sh",
    "stars": 16438,
    "language": "TypeScript",
    "license": "Apache-2.0",
    "topics": [
      "ai-sdk",
      "chatgpt",
      "nextjs",
      "notion",
      "openai",
      "prosemirror"
    ],
    "category": "personal",
    "updatedAt": "2025-01-18T14:26:33Z"
  },
  {
    "slug": "trigger-dev",
    "name": "trigger.dev",
    "owner": "triggerdotdev",
    "repo": "triggerdotdev/trigger.dev",
    "description": "Trigger.dev – build and deploy durable AI agents and workflows",
    "homepage": "https://trigger.dev/changelog",
    "stars": 16263,
    "language": "TypeScript",
    "license": "Apache-2.0",
    "topics": [
      "ai",
      "ai-agent-framework",
      "ai-agents",
      "automation",
      "background-jobs",
      "mcp"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T18:06:02Z"
  },
  {
    "slug": "documenso",
    "name": "documenso",
    "owner": "documenso",
    "repo": "documenso/documenso",
    "description": "The Open Source DocuSign Alternative.",
    "homepage": "https://documenso.com",
    "stars": 14989,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "digital-signature",
      "document-signing",
      "docusign-alternative",
      "e-signature",
      "esign",
      "esignature"
    ],
    "category": "business",
    "updatedAt": "2026-09-11T20:07:49Z"
  },
  {
    "slug": "midday",
    "name": "midday",
    "owner": "midday-ai",
    "repo": "midday-ai/midday",
    "description": "Invoicing, Time tracking, File reconciliation, Storage, Financial Overview & your own Assistant made for Freelancers",
    "homepage": "https://midday.ai",
    "stars": 14980,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "finance",
      "nextjs",
      "supabase",
      "tailwind",
      "typescript"
    ],
    "category": "business",
    "updatedAt": "2026-06-13T13:40:35Z"
  },
  {
    "slug": "commerce",
    "name": "commerce",
    "owner": "vercel",
    "repo": "vercel/commerce",
    "description": "Next.js Commerce",
    "homepage": "https://demo.vercel.store",
    "stars": 14254,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "ecommerce",
      "nextjs",
      "react",
      "shopify"
    ],
    "category": "commerce",
    "updatedAt": "2026-08-13T01:06:36Z"
  },
  {
    "slug": "formbricks",
    "name": "formbricks",
    "owner": "formbricks",
    "repo": "formbricks/formbricks",
    "description": "Open Source Qualtrics Alternative",
    "homepage": "https://formbricks.com",
    "stars": 12928,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "experience-management",
      "form",
      "forms",
      "nextjs",
      "open-source",
      "react"
    ],
    "category": "business",
    "updatedAt": "2026-09-11T18:30:15Z"
  },
  {
    "slug": "inbox-zero",
    "name": "inbox-zero",
    "owner": "elie222",
    "repo": "elie222/inbox-zero",
    "description": "The world's best AI personal assistant for email. Open source app to help you reach inbox zero fast.",
    "homepage": "https://getinboxzero.com",
    "stars": 12188,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "ai",
      "email",
      "gmail",
      "loops",
      "nextjs",
      "openai"
    ],
    "category": "personal",
    "updatedAt": "2026-09-11T17:14:04Z"
  },
  {
    "slug": "keystone",
    "name": "keystone",
    "owner": "keystonejs",
    "repo": "keystonejs/keystone",
    "description": "The superpowered headless CMS for Node.js — built with GraphQL and React",
    "homepage": "https://keystonejs.com",
    "stars": 9972,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "cms",
      "cms-framework",
      "graphql",
      "keystonejs",
      "nodejs",
      "react"
    ],
    "category": "cms",
    "updatedAt": "2026-09-02T03:43:08Z"
  },
  {
    "slug": "ghostfolio",
    "name": "ghostfolio",
    "owner": "ghostfolio",
    "repo": "ghostfolio/ghostfolio",
    "description": "Open Source Wealth Management Software. Angular + NestJS + Prisma + Nx + TypeScript 🤍",
    "homepage": "https://Ghostfol.io",
    "stars": 9277,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "angular",
      "etf",
      "finance",
      "fintech",
      "ghostfolio",
      "hacktoberfest"
    ],
    "category": "personal",
    "updatedAt": "2026-09-11T15:07:19Z"
  },
  {
    "slug": "papermark",
    "name": "papermark",
    "owner": "papermark",
    "repo": "mfts/papermark",
    "description": "Papermark is the open-source DocSend alternative  and secure data rooms with built-in analytics and custom domains.",
    "homepage": "https://www.papermark.com",
    "stars": 9159,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "dataroom",
      "next-auth",
      "nextjs",
      "open-source",
      "pdf",
      "postgresql"
    ],
    "category": "business",
    "updatedAt": "2026-08-28T15:58:25Z"
  },
  {
    "slug": "openstatus",
    "name": "openstatus",
    "owner": "openstatusHQ",
    "repo": "openstatusHQ/openstatus",
    "description": "🫖 Status page with uptime monitoring & API monitoring as code   🫖",
    "homepage": "https://openstatus.dev",
    "stars": 9106,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "alerting",
      "incident-management",
      "mcp",
      "mcp-server",
      "monitoring",
      "monitoring-as-code"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T12:33:14Z"
  },
  {
    "slug": "builder",
    "name": "builder",
    "owner": "BuilderIO",
    "repo": "BuilderIO/builder",
    "description": "Visual Development for React, Vue, Svelte, Qwik, and more",
    "homepage": "https://builder.io",
    "stars": 8825,
    "language": "TypeScript",
    "license": "MIT",
    "topics": [
      "angular",
      "builder",
      "cms",
      "drag-drop",
      "frontend",
      "gatsby"
    ],
    "category": "cms",
    "updatedAt": "2026-09-11T17:56:20Z"
  },
  {
    "slug": "platforms",
    "name": "platforms",
    "owner": "vercel",
    "repo": "vercel/platforms",
    "description": "A full-stack Next.js app with multi-tenancy.",
    "homepage": "https://vercel.pub",
    "stars": 6706,
    "language": "TypeScript",
    "license": null,
    "topics": [
      "multi-tenancy",
      "multi-tenant-applications",
      "nextjs",
      "tailwindcss",
      "vercel"
    ],
    "category": "devtools",
    "updatedAt": "2026-07-08T20:18:51Z"
  },
  {
    "slug": "typehero",
    "name": "typehero",
    "owner": "typehero",
    "repo": "typehero/typehero",
    "description": "Connect, collaborate, and grow with a community of TypeScript developers",
    "homepage": "https://typehero.dev",
    "stars": 6638,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "hacktoberfest",
      "nextjs",
      "prisma",
      "react",
      "typescript"
    ],
    "category": "personal",
    "updatedAt": "2026-09-03T20:28:09Z"
  },
  {
    "slug": "unkey",
    "name": "unkey",
    "owner": "unkeyed",
    "repo": "unkeyed/unkey",
    "description": "The Developer Platform for Modern APIs",
    "homepage": "https://go.unkey.com",
    "stars": 5435,
    "language": "Go",
    "license": "NOASSERTION",
    "topics": [
      "api",
      "api-keys",
      "authentication",
      "authorization",
      "deployment",
      "gateway"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T21:19:50Z"
  },
  {
    "slug": "rallly",
    "name": "rallly",
    "owner": "lukevella",
    "repo": "lukevella/rallly",
    "description": "Rallly is an open-source scheduling and collaboration tool designed to make organizing events and meetings easier.",
    "homepage": "https://rallly.co",
    "stars": 5256,
    "language": "TypeScript",
    "license": "AGPL-3.0",
    "topics": [
      "i18next",
      "next-auth",
      "nextjs",
      "postgresql",
      "prisma",
      "react-email"
    ],
    "category": "personal",
    "updatedAt": "2026-09-11T16:42:14Z"
  },
  {
    "slug": "tolgee-platform",
    "name": "tolgee-platform",
    "owner": "tolgee",
    "repo": "tolgee/tolgee-platform",
    "description": "Developer & translator friendly web-based localization platform",
    "homepage": "https://tolgee.io",
    "stars": 4099,
    "language": "TypeScript",
    "license": "NOASSERTION",
    "topics": [
      "angular",
      "hacktoberfest",
      "i18n",
      "i18next",
      "internationalization",
      "javascript"
    ],
    "category": "devtools",
    "updatedAt": "2026-09-11T15:29:12Z"
  }
]
