/**
 * Generated by scripts/generate-registry-files.mjs — do not edit by hand.
 *
 * Imported components are stored under a prefixed key when their name collides
 * with one already in the registry. The code viewer maps them back so the
 * import path shown is the one a consumer would actually write.
 */
export const IMPORT_ALIASES: Record<string, string> = {
  "kokonut-ui-bento-grid": "bento-grid",
  "kokonut-ui-gradient-button": "gradient-button",
  "magic-ui-dot-pattern": "dot-pattern",
  "magic-ui-file-tree": "file-tree",
  "magic-ui-marquee": "marquee",
  "magic-ui-number-ticker": "number-ticker",
  "magic-ui-shimmer-button": "shimmer-button",
}
