// Generated by scripts/fetch-shadcn-registries.mjs — do not edit by hand.
// Source: https://ui.shadcn.com/r/registries.json
// Snapshot taken: 2026-09-11T16:15:00.558Z

export interface ShadcnRegistry {
  /** e.g. "@magicui" — usable as `npx shadcn add @magicui/marquee` */
  namespace: string
  homepage: string | null
  /** URL template, e.g. "https://magicui.design/r/{name}.json" */
  url: string
  description: string
  status: "healthy" | "degraded" | "observing" | "unavailable" | "unknown"
  /** upstream health score out of 100 */
  score: number | null
  /** uptime over the last 30 days, as a percentage */
  availability30d: number | null
}

export const REGISTRIES_SNAPSHOT_AT = "2026-09-11T16:15:00.558Z"

export const REGISTRIES: ShadcnRegistry[] = [
  {
    "namespace": "@1st-pouf",
    "homepage": "https://1st-pouf.worksonmy.dev",
    "url": "https://1st-pouf.worksonmy.dev/r/{name}.json",
    "description": "Puffy, pastel claymorphism components and app blocks for React, built with Tailwind CSS v4 and Radix UI.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@7ovr",
    "homepage": "https://7ovr.com",
    "url": "https://7ovr.com/r/{name}.json",
    "description": "Free, production-ready UI blocks for marketing pages and application dashboards, built on Base UI and installable with the shadcn CLI.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99
  },
  {
    "namespace": "@8bitcn",
    "homepage": "https://www.8bitcn.com",
    "url": "https://www.8bitcn.com/r/{name}.json",
    "description": "A set of 8-bit styled retro components. Works with your favorite frameworks. Open Source. Open Code.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@8starlabs-ui",
    "homepage": "https://ui.8starlabs.com",
    "url": "https://ui.8starlabs.com/r/{name}.json",
    "description": "A set of beautifully designed components designed for developers who want niche, high-utility UI elements that you won't find in standard libraries.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99
  },
  {
    "namespace": "@ai-elements",
    "homepage": "https://ai-sdk.dev/elements",
    "url": "https://ai-sdk.dev/elements/api/registry/{name}.json",
    "description": "Pre-built components like conversations, messages and more to help you build AI-native applications faster.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@ai2",
    "homepage": "https://ai2.design",
    "url": "https://ai2.design/r/{name}.json",
    "description": "Agent-native design system for the shadcn CLI: 51 base components with a full variant, tone and size matrix on an OKLCH token layer, plus 307 styled variations. MIT.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@aicanvas",
    "homepage": "https://aicanvas.me",
    "url": "https://aicanvas.me/r/{name}.json",
    "description": "Animated React components with AI reproduction prompts, alongside full design systems and templates. Install via CLI or aicanvas MCP, compatible with Claude Code, Codex, and Cursor.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@animbits",
    "homepage": "https://animbits.dev",
    "url": "https://animbits.dev/r/{name}.json",
    "description": "AnimBits is a collection animated UI components for React that use Framer Motion. The components provided include buttons, cards, text, icons, lists, loaders, and page transitions, animation hooks all of which have general-purpose effects that are not flashy and easy on the eyes, making them easy to use.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@assistant-ui",
    "homepage": "https://www.assistant-ui.com",
    "url": "https://r.assistant-ui.com/{name}.json",
    "description": "Radix-style React primitives for AI chat with adapters for AI SDK, LangGraph, Mastra, and custom backends.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@atroui",
    "homepage": "https://www.atroui.com",
    "url": "https://www.atroui.com/r/{name}.json",
    "description": "Dark-first React / Next.js components and marketing blocks. Install with the shadcn CLI and own the source.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@beui",
    "homepage": "https://beui.dev",
    "url": "https://beui.dev/r/{name}.json",
    "description": "Bespoke motion components for React. Copy-paste components with shadcn-compatible installs, Tailwind CSS v4, and Motion.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@blode",
    "homepage": "https://blode.co/ui",
    "url": "https://blode.co/ui/r/{name}.json",
    "description": "An open-source registry of accessible React components built on Base UI and Tailwind CSS v4. Install with one command, then own the source.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@boldkit",
    "homepage": "https://boldkit.dev",
    "url": "https://boldkit.dev/r/{name}.json",
    "description": "Neubrutalism component library with 43 components, 42 SVG shapes, thick borders, and hard shadows. Supports React, Vue, and Nuxt. Built on shadcn/ui.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@bundui",
    "homepage": "https://bundui.io",
    "url": "https://bundui.io/r/{name}.json",
    "description": "A collection of 150+ handcrafted UI components built with Tailwind CSS and shadcn/ui, covering marketing, e-commerce, dashboards, real estate, and more.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@chamaac",
    "homepage": "https://chamaac.com",
    "url": "https://chamaac.com/r/{name}.json",
    "description": "A collection of beautiful, animated components to elevate your web projects instantly.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@componentry",
    "homepage": "https://componentry.fun",
    "url": "https://componentry.fun/r/{name}.json",
    "description": "Beautiful, interactive React + Tailwind components for modern product UIs.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@cubby-ui",
    "homepage": "https://www.cubby-ui.dev",
    "url": "https://www.cubby-ui.dev/r/{name}.json",
    "description": "An opinionated component library with curated styling and simplified patterns for common use cases. Built on Base UI and Tailwind CSS 4.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@delta",
    "homepage": "https://deltacomponents.dev",
    "url": "https://deltacomponents.dev/r/{name}.json",
    "description": "A shadcn registry for AI and media-rich interfaces — streaming LLM chat, zoomable images, swipeable card decks, interactive maps, plus dashboard and landing-page blocks.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99
  },
  {
    "namespace": "@dotmatrix",
    "homepage": "https://dotmatrix.zzzzshawn.cloud",
    "url": "https://dotmatrix.zzzzshawn.cloud/r/{name}.json",
    "description": "Production-ready dot-matrix loading components for React, featuring square, circular, and triangle animations with polished motion.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@eldoraui",
    "homepage": "https://eldoraui.site",
    "url": "https://eldoraui.site/r/{name}.json",
    "description": "An open-source, modern UI component library for React, built with TypeScript, Tailwind CSS, and Framer Motion. Eldora UI offers beautifully crafted, reusable components designed for performance and elegance.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@elements",
    "homepage": "https://www.tryelements.dev",
    "url": "https://www.tryelements.dev/r/{name}.json",
    "description": "Full-stack shadcn/ui components that go beyond UI. Add auth, monetization, uploads, and AI to your app in seconds.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@evilcharts",
    "homepage": "https://evilcharts.com",
    "url": "https://evilcharts.com/r/{name}.json",
    "description": "EvilCharts is an open-source chart UI website built with shadcn and Recharts, beautifully designed and handcrafted.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@flagcn",
    "homepage": "https://flagcn.dev",
    "url": "https://flagcn.dev/r/{name}.json",
    "description": "Accessible, source-owned flag components for shadcn/ui with 306 flags in SVG, PNG, WebP, and JPEG plus 4:3, 1:1, and original ratios.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@flx",
    "homepage": "https://ui.flexnative.com",
    "url": "https://ui.flexnative.com/r/{name}.json",
    "description": "A collection of customizable UI blocks with interactive live previews",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@framecn",
    "homepage": "https://framecn.vercel.app",
    "url": "https://framecn.vercel.app/r/{name}.json",
    "description": "Beautiful videos, made simple. Ready to use, customizable video components for React.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@gammaui",
    "homepage": "https://www.gammaui.com",
    "url": "https://www.gammaui.com/r/{name}.json",
    "description": "Beautifully designed landing page components built with React & Tailwind CSS & Motion.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@gc-solid",
    "homepage": "https://binnodon.github.io/gc-solid-ui",
    "url": "https://binnodon.github.io/gc-solid-ui/r/{name}.json",
    "description": "SolidJS port of shadcn-ui components built with Kobalte primitives. 57+ components with full TypeScript support and Vega theme.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@glasscn",
    "homepage": "https://glasscn-components.vercel.app/",
    "url": "https://glasscn-components.vercel.app/r/{name}.json",
    "description": "A shadcn-compatible registry of glassmorphism components inspired by Apple",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@heroicons-animated",
    "homepage": "https://www.heroicons-animated.com/",
    "url": "https://www.heroicons-animated.com/r/{name}.json",
    "description": "An open-source collection of 316 beautifully animated heroicons for your projects.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@hextaui",
    "homepage": "https://hextaui.com",
    "url": "https://hextaui.com/r/{name}.json",
    "description": "Ready-to-use foundation components/blocks built on top of shadcn/ui.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@hirael",
    "homepage": "https://hirael.com",
    "url": "https://hirael.com/r/{name}.json",
    "description": "The components shadcn/ui doesn't ship. A collection of high-utility React components built on top of shadcn/ui.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@honestui",
    "homepage": "https://www.honestui.com",
    "url": "https://www.honestui.com/r/{name}.json",
    "description": "React UI components, animated interactions, shaders, and charts distributed as editable source.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@hugeicons-animated",
    "homepage": "https://hugeicons-animated.com",
    "url": "https://hugeicons-animated.com/r/{name}.json",
    "description": "An open-source collection of animated Hugeicons for React.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@ilinxa",
    "homepage": "https://ui.ilinxa.com",
    "url": "https://ui.ilinxa.com/r/{name}.json",
    "description": "High-level composed components for shadcn/ui — kanban, gantt, calendar, media editors, story viewers, flow canvas, forms, and more, each with optional demo fixtures.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@intentui",
    "homepage": "https://intentui.com",
    "url": "https://intentui.com/r/{name}",
    "description": "Accessible React component library to copy, customize, and own your UI.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@lucide-animated",
    "homepage": "https://lucide-animated.com",
    "url": "https://lucide-animated.com/r/{name}.json",
    "description": "An open-source collection of smooth animated lucide icons for your projects",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@magicui",
    "homepage": "https://magicui.design",
    "url": "https://magicui.design/r/{name}",
    "description": "UI Library for Design Engineers. 150+ free and open-source animated components and effects built with React, Typescript, Tailwind CSS, and Motion. Perfect companion for shadcn/ui.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@moduix-react",
    "homepage": "https://moduix.dev",
    "url": "https://moduix.dev/r/react/{name}.json",
    "description": "Ark-first React components, blocks, and themes with native CSS, available as a package or a shadcn-compatible copy-owned registry.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@motion-lexicon",
    "homepage": "https://motion-lexicon.pages.dev",
    "url": "https://motion-lexicon.pages.dev/r/{name}.json",
    "description": "Copy-ready React page blocks and motion components with bilingual previews, reduced-motion paths, and shadcn Registry delivery.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@motiq",
    "homepage": "https://motiq.dev",
    "url": "https://motiq.dev/r/{name}.json",
    "description": "Production-ready animated React and Next.js components — accessible, reduced-motion-safe and RSC-safe — installable as editable source with the shadcn CLI. Free and open source.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@ncdai",
    "homepage": "https://chanhdai.com/components",
    "url": "https://chanhdai.com/r/{name}.json",
    "description": "Pixel-perfect, uniquely crafted.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@neon-ui",
    "homepage": "https://ui.neon.com",
    "url": "https://ui.neon.com/r/{name}.json",
    "description": "Production-ready components for agent platforms built on Neon. Database branching, connection strings, usage metering and project management UI, built with Base UI and Tailwind v4.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@nusaiba",
    "homepage": "https://nusaiba.dev",
    "url": "https://nusaiba.dev/r/base-nova/{name}.json",
    "description": "Motion-first shadcn marketing blocks for landing pages — heroes, pricing, FAQs, footers, and more. Built on base-nova with intentional animation and CLI install.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@odysseyui",
    "homepage": "https://www.odysseyui.com/docs",
    "url": "https://www.odysseyui.com/r/{name}.json",
    "description": "A design focused component library for Next.js, built for speed, flexibility and developer experience.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@optics",
    "homepage": "https://optics.agusmayol.com.ar",
    "url": "https://optics.agusmayol.com.ar/r/{name}.json",
    "description": "A design system that distributes re-styled components, utilities, and hooks ready to use.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@oui",
    "homepage": "https://oui.mw10013.workers.dev",
    "url": "https://oui.mw10013.workers.dev/r/{name}.json",
    "description": "React Aria Components with shadcn characteristics.Copy-and-paste react aria components that run side-by-side with shadcn components.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@paletteui",
    "homepage": "https://paletteui.xyz",
    "url": "https://paletteui.xyz/r/{name}.json",
    "description": "Curated OKLCH color themes for shadcn/ui + visual theme editor with CSS, Tailwind v4, and Figma export.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99
  },
  {
    "namespace": "@payload-components",
    "homepage": "https://www.payload-components.xyz",
    "url": "https://www.payload-components.xyz/r/{name}.json",
    "description": "MIT registry of typed Payload CMS blocks for Payload v3 + Next.js. Each block installs as reviewable source; the companion CLI also wires collection config, RenderBlocks, types, and the admin import map.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@persianlabsui",
    "homepage": "https://ui.persian-labs.ir",
    "url": "https://ui.persian-labs.ir/r/{name}.json",
    "description": "RTL-first, copy-paste React components and UI blocks for Persian interfaces, built on Base UI and Tailwind CSS. Includes unique Persian-focused patterns with full LTR support.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@plate",
    "homepage": "https://platejs.org",
    "url": "https://platejs.org/r/{name}.json",
    "description": "AI-powered rich text editor for React.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@preskok",
    "homepage": "https://ui-three-mu.vercel.app",
    "url": "https://ui-three-mu.vercel.app/r/{name}.json",
    "description": "Accessible, production-ready React components built with React Aria Components and Tailwind CSS.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@prosekit",
    "homepage": "https://prosekit.dev",
    "url": "https://prosekit.dev/r/{name}.json",
    "description": "Powerful and flexible rich text editor for React, Vue, Preact, Svelte, and SolidJS.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@pulld",
    "homepage": "https://pulld.pages.dev",
    "url": "https://pulld.pages.dev/r/{name}.json",
    "description": "Typed, accessible, theme-aware React/Tailwind components installable by the shadcn CLI or your AI coding agent. Free atoms plus composed Pro blocks.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@react-aria",
    "homepage": "https://react-aria.adobe.com",
    "url": "https://react-aria.adobe.com/registry/{name}.json",
    "description": "Customizable Tailwind and Vanilla CSS components with adaptive interactions, top-tier accessibility, and internationalization.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@react-bits",
    "homepage": "https://reactbits.dev",
    "url": "https://reactbits.dev/r/{name}.json",
    "description": "A large collection of animated, interactive & fully customizable React components for building memorable websites. From smooth text animations all the way to eye-catching backgrounds, you can find it here.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@remocn",
    "homepage": "https://www.remocn.dev/",
    "url": "https://www.remocn.dev/r/{name}.json",
    "description": "Production-ready components for Remotion - text animations, backgrounds, transitions, UI blocks, and full scene compositions",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@seamui",
    "homepage": "https://seamui.dev",
    "url": "https://seamui.dev/r/{name}.json",
    "description": "Own-your-code components rebuilt on Base UI with a motion.dev feel layer — springs, touch feedback, and depth — plus an agent-workbench tier (composer, voice, status, connectors) for AI-era interfaces.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcnmaps",
    "homepage": "https://shadcnmaps.com",
    "url": "https://shadcnmaps.com/r/{name}.json",
    "description": "Beautiful map components powered by pure SVG.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@soundcn",
    "homepage": "https://soundcn.xyz",
    "url": "https://soundcn.xyz/r/{name}.json",
    "description": "Large collection of game, interface, retro, and voice sound effects for web applications",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@spectrumui",
    "homepage": "https://ui.spectrumhq.in",
    "url": "https://ui.spectrumhq.in/r/{name}.json",
    "description": "A modern component library built with shadcn/ui and Tailwind CSS. Spectrum UI offers elegant, responsive components and smooth animations designed for high-quality interfaces.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@svelte-bits",
    "homepage": "https://sveltebits.xyz",
    "url": "https://sveltebits.xyz/r/{name}.json",
    "description": "An open source collection of high quality, animated, interactive & fully customizable Svelte components for building stunning, memorable user interfaces.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@thegridcn",
    "homepage": "https://thegridcn.com",
    "url": "https://thegridcn.com/r/{name}.json",
    "description": "A Tron-inspired shadcn/ui theme system with Greek god color schemes, glow intensity levels, and sci-fi components like DataCard, HUD, Radar, and more.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@ui-layouts",
    "homepage": "https://ui-layouts.com/",
    "url": "https://ui-layouts.com/r/{name}.json",
    "description": "UI Layouts offers components, effects, design tools, and ready-made blocks that make building modern interfaces more efficient—built with React, Next.js, Tailwind CSS, and shadcn/ui.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@uiable",
    "homepage": "https://uiable.com",
    "url": "https://uiable.com/r/{name}.json",
    "description": "Free, open-source UI component library built with Next.js, React 19, Tailwind CSS v4, and shadcn/ui — beautifully designed components you can copy, customize, and make your own.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99
  },
  {
    "namespace": "@usva",
    "homepage": "https://usva.build",
    "url": "https://usva.build/r/{name}.json",
    "description": "A React design language in three themes, where kajo is atmospheric and dark, sisu is dense and quick, and savi is the light ground. One token vocabulary underneath, including WebGL atmospheres that honour reduced-motion. Every component installs from npm or copies in from this registry.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@vllnt-ui",
    "homepage": "https://ui.vllnt.com",
    "url": "https://ui.vllnt.com/r/{name}.json",
    "description": "VLLNT UI — agent-first React components for AI-native products, from UI primitives to finance and ops domains. Accessible, Radix + Tailwind, you own the code.",
    "status": "healthy",
    "score": 98,
    "availability30d": 98.3
  },
  {
    "namespace": "@vue-bits",
    "homepage": "https://vue-bits.dev",
    "url": "https://vue-bits.dev/r/{name}.json",
    "description": "An open source collection of high quality, animated, interactive & fully customizable Vue components for building stunning, memorable user interfaces.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@whiskeyjack",
    "homepage": "https://whiskeyjack.net",
    "url": "https://whiskeyjack.net/r/{name}.json",
    "description": "A Tauri-first design system: thumb-first components with Metro-style pivot navigation, frosted bottom nav, and tap-again confirmations, on a CSS-variable token pipeline. Hardened across nine shipping apps before extraction.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@wigggle-ui",
    "homepage": "https://wigggle-ui.vercel.app",
    "url": "https://wigggle-ui.vercel.app/r/{name}.json",
    "description": "A beautiful collection of copy-and-paste widgets for your next project.",
    "status": "healthy",
    "score": 98,
    "availability30d": 99.3
  },
  {
    "namespace": "@23rd",
    "homepage": "https://23rd.dev",
    "url": "https://23rd.dev/r/{name}.json",
    "description": "Opinionated components for shippers.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@aevr",
    "homepage": "https://ui.aevr.online",
    "url": "https://ui.aevr.online/r/{name}.json",
    "description": "A small collection of focused, production‑ready components and primitives for React/Next.js projects—built on shadcn/ui and complementary libraries.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@afterglow",
    "homepage": "https://afterglow.thebuilder.dk",
    "url": "https://afterglow.thebuilder.dk/r/{name}.json",
    "description": "A complete terminal UI system for shadcn with Base UI components, terminal-specific building blocks, and eight phosphor color themes.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.1
  },
  {
    "namespace": "@agents-ui",
    "homepage": "https://livekit.com/ui",
    "url": "https://livekit.com/ui/r/{name}.json",
    "description": "This is a shadcn/ui component registry that distributes copy-paste React components for building LiveKit AI Agent interfaces.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@algolia",
    "homepage": "https://sitesearch.algolia.com",
    "url": "https://sitesearch.algolia.com/r/{name}.json",
    "description": "Enterprises and developers use Algolia's AI search infrastructure to understand users and show them what they're looking for.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@approvals-ui",
    "homepage": "https://approvals-ui.vercel.app",
    "url": "https://approvals-ui.vercel.app/r/{name}.json",
    "description": "Approval workflow components for React Flow: quorum gates, amount thresholds, a policy lint (segregation of duties, single approver on high value), and plain-language editing behind a human review gate.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@arc",
    "homepage": "https://witharc.co/components",
    "url": "https://witharc.co/r/{name}.json",
    "description": "Animated, accessible UI components built with React and Tailwind CSS.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@basecn",
    "homepage": "https://basecn.dev",
    "url": "https://basecn.dev/r/{name}.json",
    "description": "Beautifully crafted shadcn/ui components powered by Base UI",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@baselayer",
    "homepage": "https://www.baselayer.dev",
    "url": "https://www.baselayer.dev/r/{name}.json",
    "description": "A collection of components built on React Aria, Tailwind CSS, and tailwind-variants.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@benday",
    "homepage": "https://benday.kacemmathlouthi.dev",
    "url": "https://benday.kacemmathlouthi.dev/r/{name}.json",
    "description": "Turn any logo into an animated Ben-Day dot field: a thinking indicator for AI and agent interfaces, baked from your own mark.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@better-auth-ui",
    "homepage": "https://better-auth-ui.com",
    "url": "https://better-auth-ui.com/r/{style}/{name}.json",
    "description": "Drop-in authentication components for Better Auth applications.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@better-upload",
    "homepage": "https://better-upload.com",
    "url": "https://better-upload.com/r/{name}.json",
    "description": "Simple and easy file uploads for React. Upload directly to any S3-compatible service with minimal setup.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@brainless",
    "homepage": "https://brainless.swerdlow.dev",
    "url": "https://brainless.swerdlow.dev/r/{name}.json",
    "description": "Claude Code, Codex, and Grok interfaces as shadcn components — accessible React terminal-agent UI for docs, demos, and product surfaces.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@brut-ui",
    "homepage": "https://www.brut-ui.site",
    "url": "https://www.brut-ui.site/r/{name}.json",
    "description": "Production-minded neo-brutalist shadcn components with three configurable flavours, strengths, and radius modes.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@cardcn",
    "homepage": "https://cardcn.dev",
    "url": "https://cardcn.dev/r/{name}.json",
    "description": "A set of beautifully-designed shadcn card components",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@channel3",
    "homepage": "https://trychannel3.com/developers/ui",
    "url": "https://ui.trychannel3.com/r/{name}.json",
    "description": "Open-source React components for building shopping experiences on the Channel3 product API: search, filters, product detail, offer comparison, and price history.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@clerk",
    "homepage": "https://clerk.com/docs/guides/development/shadcn-cli",
    "url": "https://clerk.com/r/{name}.json",
    "description": "The easiest way to add authentication and user management to your application. Purpose-built for React, Next.js, Remix, and The Modern Web.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@commercn",
    "homepage": "https://commercn.com",
    "url": "https://commercn.com/r/{name}.json",
    "description": "Shadcn UI Blocks for Ecommerce websites",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@contentbit",
    "homepage": "https://contentbit.dev",
    "url": "https://contentbit.dev/r/{name}.json",
    "description": "React components that render Content Blocks: plain Markdown with schema-validated directive blocks. Built for content written by humans, CMSes, and LLMs.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@corr",
    "homepage": "https://ui.corr.sh",
    "url": "https://ui.corr.sh/r/{name}.json",
    "description": "A collection of shadcn-based React components, charts, animated components, and blocks built over time.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@diklein",
    "homepage": "https://diklein.com/components",
    "url": "https://diklein.com/r/{name}.json",
    "description": "A growing collection of design-forward React components by Dave Klein, extracted from the components powering diklein.com.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@einui",
    "homepage": "https://ui.eindev.ir",
    "url": "https://ui.eindev.ir/r/{name}.json",
    "description": "Beautiful, responsive Shadcn components with frosted glass morphism. Built for modern web applications with full dark mode support.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@evex",
    "homepage": "https://evex.sh",
    "url": "https://evex.sh/r/{name}.json",
    "description": "Installable AI agent recipes for Eve apps, including PR review, data analysis, and workflow automation agents.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@fab-ui",
    "homepage": "https://fab-ui.com",
    "url": "https://fab-ui.com/r/{name}.json",
    "description": "A collection of beautifully designed UI components for building modern web applications.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@flightcn",
    "homepage": "https://flightcn.yencheng.dev",
    "url": "https://flightcn.yencheng.dev/r/{name}.json",
    "description": "Flight routes on interactive maps with great-circle arcs, airport markers, multi-leg journeys, and optional animation, built for mapcn.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@flowkit-ui",
    "homepage": "https://flowkit-ui.vzkiss.com",
    "url": "https://flowkit-ui.vzkiss.com/r/{name}.json",
    "description": "Opinionated, accessible components on Base UI and shadcn-style primitives — starting with a Creatable Combobox.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@flowui",
    "homepage": "https://flowui-registry.vercel.app",
    "url": "https://flowui-registry.vercel.app/r/{name}.json",
    "description": "Everyday use react components to make the development flow easier for the devs.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@forgeui",
    "homepage": "https://forgeui.in/",
    "url": "https://forgeui.in/r/{name}.json",
    "description": "Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@formcn",
    "homepage": "https://formcn.dev",
    "url": "https://formcn.dev/r/{name}.json",
    "description": "Build production-ready forms with a few clicks using shadcn components and modern tools.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@gaia",
    "homepage": "https://ui.heygaia.io",
    "url": "https://ui.heygaia.io/r/{name}.json",
    "description": "Production-ready UI components designed for building beautiful AI assistants and conversational interfaces, from the team behind GAIA.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@gamekitui",
    "homepage": "https://gamekitui.com",
    "url": "https://gamekitui.com/r/{name}.json",
    "description": "Drop-in, themeable browser games for shadcn — Snake, 2048, Minesweeper, and more. Each is a single self-contained file with zero dependencies.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@gamifykit",
    "homepage": "https://gamifykit.com",
    "url": "https://gamifykit.com/r/{name}.json",
    "description": "A collection of fully composable components that extend shadcn/ui with a focus on common gamification UI patterns.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@gooseui",
    "homepage": "https://gooseui.pro",
    "url": "https://gooseui.pro/r/{name}.json",
    "description": "Open source component library with animated components, beautiful effects, and custom toast notifications. Built with Radix UI and Tailwind CSS.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@gpt-vis",
    "homepage": "https://gpt-vis.antv.vision",
    "url": "https://gpt-vis.antv.vision/r/{name}.json",
    "description": "AI-native visualization components for LLM projects. Render 26 chart types from vis syntax strings or config objects.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@gymnopedies",
    "homepage": "https://gymnopedies.shoota.work",
    "url": "https://gymnopedies.shoota.work/r/{name}.json",
    "description": "A dark, serif, glow-leaning shadcn registry of read-only components for blogs, essays, and long-form reading experiences — inspired by the quiet, candlelit cabaret of Erik Satie's Gymnopédies.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@ha-components",
    "homepage": "https://hacomponents.keshuac.com",
    "url": "https://hacomponents.keshuac.com/r/{name}.json",
    "description": "A collection of customisable components to build Home Assistant dashboards.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@indiacn",
    "homepage": "https://indiacn.in",
    "url": "https://indiacn.in/r/{name}.json",
    "description": "UX4G 2.0 design system for India — many accessible React components and an 8-color theme preset for native apps.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@inferencesh",
    "homepage": "https://ui.inference.sh",
    "url": "https://ui.inference.sh/r/{name}.json",
    "description": "batteries-included agent components by inference.sh. chat interfaces with streaming, tool invocation rendering, syntax-highlighted code blocks, markdown renderer, and more.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@interior",
    "homepage": "https://www.interior.dev",
    "url": "https://www.interior.dev/r/{name}.json",
    "description": "Copy-paste React micro-interactions: a headless hook plus a styled example in one self-contained file, with motion as the only dependency.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@joyco",
    "homepage": "https://registry.joyco.studio",
    "url": "https://registry.joyco.studio/r/{name}.json",
    "description": "Components including MobileMenu, ScrollArea with gradients, Chat UI, HLSVideoPlayer, and Marquee.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@kapwa",
    "homepage": "https://kapwa-two.vercel.app",
    "url": "https://kapwa-two.vercel.app/r/{name}.json",
    "description": "Cleanly designed components purposely built for open-source government portals.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@kinetic",
    "homepage": "https://kinetic.itsjay.in",
    "url": "https://kinetic.itsjay.in/r/{name}.json",
    "description": "A Figma-like scrub number field for shadcn/ui (base-nova). Digit animation by Calligraph.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@liquefy-ui",
    "homepage": "https://liquefy-ui.com",
    "url": "https://liquefy-ui.com/r/{name}.json",
    "description": "Liquid Glass components for React: WebGL edge refraction and pointer-driven springs over accessible Base UI primitives. TypeScript, RSC-ready, with an MCP server.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@lmscn",
    "homepage": "https://lmscn.vercel.app",
    "url": "https://lmscn.vercel.app/r/{name}.json",
    "description": "LMS components for building interactive learning experiences — quiz, flashcards, matching, fill-in-the-blank, word scramble, sequencing, reading comprehension, spaced repetition and more.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@loading-ui",
    "homepage": "https://loading-ui.com",
    "url": "https://loading-ui.com/r/{name}.json",
    "description": "Spinners, loaders, and loading animations for modern web apps. Free and open-source.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@lytenyte",
    "homepage": "https://www.1771technologies.com",
    "url": "https://www.1771technologies.com/r/{name}.json",
    "description": "LyteNyte Grid is a high performance, light weight, headless, React data grid. Our registry provides LyteNyte Grid themed using Tailwind and the Shadcn theme variables.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@mapcn",
    "homepage": "https://mapcn.dev",
    "url": "https://mapcn.dev/r/{name}.json",
    "description": "Beautiful maps, made simple. Ready to use, customizable map components for React. Built on MapLibre. Styled with Tailwind CSS.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@mediadrop",
    "homepage": "https://www.mediadrop.dev",
    "url": "https://www.mediadrop.dev/r/{name}.json",
    "description": "Drag-and-drop file upload blocks for React built on react-mediadrop — dropzone, avatar uploader, multi-file upload form, and direct-to-S3 upload.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@mksingh",
    "homepage": "https://mksingh.dev/docs",
    "url": "https://mksingh.dev/r/{name}.json",
    "description": "A personal registry of production-ready ShadCN components and utilities. Everything is built to drop into your existing ShadCN project with no extra setup.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@motokoui",
    "homepage": "https://motokoui.com",
    "url": "https://www.motokoui.com/r/{name}.json",
    "description": "Components, application blocks, templates, and starter kits for modern React applications.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@nexus-ui",
    "homepage": "https://nexus-ui.dev",
    "url": "https://nexus-ui.dev/r/{name}.json",
    "description": "Open-source component library of composable, copy-paste primitives for building AI interfaces (chat, streaming, multimodal)",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@nteract",
    "homepage": "https://nteract-elements.vercel.app/",
    "url": "https://nteract-elements.vercel.app/r/{name}.json",
    "description": "Components for interactive computing notebooks.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@nuqs",
    "homepage": "https://nuqs.dev/registry",
    "url": "https://nuqs.dev/r/{name}.json",
    "description": "Custom parsers, adapters and utilities from the community for type-safe URL state management.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@ogimagecn",
    "homepage": "https://ogimagecn.vercel.app",
    "url": "https://ogimagecn.vercel.app/r/{name}.json",
    "description": "Beautiful OG images, made simple. Ready to use, customizable Open Graph image components for React.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@onchain-ui",
    "homepage": "https://onchain-ui.dev",
    "url": "https://onchain-ui.dev/r/{name}.json",
    "description": "Web3 components for shadcn apps. Wallet identity, token logos, balances, and market UI primitives for EVM products.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@openmirai",
    "homepage": "https://www.openmirai.dev",
    "url": "https://www.openmirai.dev/r/{name}.json",
    "description": "Open-source React and TypeScript tools from OpenMirai.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@openstatus",
    "homepage": "https://openstatus.dev/registry",
    "url": "https://openstatus.dev/r/{name}.json",
    "description": "Hand-crafted, accessible components for building beautiful status pages.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@paddle",
    "homepage": "https://developer.paddle.com/",
    "url": "https://developer.paddle.com/r/{name}.json",
    "description": "Drop-in components for building checkouts, pricing pages, and subscription management screens using Paddle Billing.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@pastecn",
    "homepage": "https://pastecn.com",
    "url": "https://pastecn.com/r/{name}",
    "description": "pastebin + shadcn = pastecn. Paste your code and get a shadcn-compatible registry URL instantly.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@prompt-kit",
    "homepage": "https://www.prompt-kit.com",
    "url": "https://www.prompt-kit.com/c/{name}.json",
    "description": "Core building blocks for AI apps. High-quality, accessible, and customizable components for AI interfaces.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@pulkitxm",
    "homepage": "https://pulkit.page",
    "url": "https://pulkit.page/components/{name}.json",
    "description": "Animated shadcn components powered by GSAP and Framer Motion. Built for expressive UIs.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@ramonclaudio-coderabbit",
    "homepage": "https://ramonclaudio.com/registries/coderabbit",
    "url": "https://coderabbit-shadcn-registry.vercel.app/r/{name}.json",
    "description": "A framework-agnostic API client, pluggable storage adapters (LocalStorage, Convex, Supabase, PostgreSQL, MySQL), and React components for generating developer activity reports.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@react-slot",
    "homepage": "https://react-slot.vercel.app/",
    "url": "https://react-slot.vercel.app/r/{name}.json",
    "description": "Vue-style slot composition for React - Fine-grained control over component composition",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcndesign",
    "homepage": "https://www.shadcndesign.com",
    "url": "https://shadcndesign-free.vercel.app/r/{name}.json",
    "description": "A growing collection of high-quality blocks and themes for shadcn/ui.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcnloaders",
    "homepage": "https://shadcn-loaders.vercel.app",
    "url": "https://shadcn-loaders.vercel.app/r/{name}.json",
    "description": "A public registry of shadcn-inspired animated loaders and loading states.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@skiper-ui",
    "homepage": "https://skiper-ui.com/",
    "url": "https://skiper-ui.com/registry/{name}.json",
    "description": "Brand new uncommon components for your Next.js project. Use with ease through shadcn CLI 3.0, featuring fast-growing components and collections that are easy to edit and use.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@slide-cn",
    "homepage": "https://slide-cn.com",
    "url": "https://slide-cn.com/r/{name}.json",
    "description": "A component library to build slide decks using code.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@snapcn",
    "homepage": "https://snapcn.dev",
    "url": "https://snapcn.dev/r/{name}.json",
    "description": "Remotion video components for React. Text reveals, karaoke captions, device mockups, logo stings and full scenes, installed with the CLI and owned as source.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@solaceui",
    "homepage": "https://www.solaceui.com",
    "url": "https://www.solaceui.com/r/{name}.json",
    "description": "Production-ready and tastefully crafted sections, animated components, and full-page templates for Next.js, Tailwind CSS & Motion",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@sona-ui",
    "homepage": "https://sonaui.com",
    "url": "https://sonaui.com/r/{name}.json",
    "description": "A modern UI component library built with React and TailwindCSS to help you build beautiful and accessible web applications faster.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.2
  },
  {
    "namespace": "@stepper",
    "homepage": "https://francozeta-stepper.vercel.app",
    "url": "https://francozeta-stepper.vercel.app/{name}.json",
    "description": "A modern, accessible and composable Stepper component for React and Tailwind CSS. Built for shadcn/ui-style workflows with registry-first distribution.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@terrae",
    "homepage": "https://www.terrae.dev",
    "url": "https://www.terrae.dev/{name}.json",
    "description": "Composable, animated map components for React. Built with TypeScript, Tailwind CSS, Mapbox GL JS, and MapLibre GL. Perfect companion for shadcn/ui.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@tetra-ui",
    "homepage": "https://tetra-ui.com",
    "url": "https://tetra-ui.com/r/{name}.json",
    "description": "Delightful components for a clean, accessible and modern component library for React Native.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@threecn",
    "homepage": "https://threecn.dev",
    "url": "https://threecn.dev/r/{name}.json",
    "description": "3D scenes for shadcn/ui. Theme-aware React Three Fiber components, one command away.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@toc-cn",
    "homepage": "https://tocn.vercel.app",
    "url": "https://tocn.vercel.app/r/{name}.json",
    "description": "Documentation-style in-page table of contents with scroll spy, animated SVG tree indicator, and mobile sticky collapsible.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@tokenui",
    "homepage": "https://www.tokenui.dev",
    "url": "https://www.tokenui.dev/r/{name}.json",
    "description": "Beautiful, interactive documentation components for your design tokens following industry standards.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@tool-ui",
    "homepage": "https://www.tool-ui.com",
    "url": "https://www.tool-ui.com/r/{name}.json",
    "description": "Open source React components for rendering AI tool call widgets and rich assistant outputs.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@tour",
    "homepage": "https://onboarding-tour.vercel.app",
    "url": "https://onboarding-tour.vercel.app/r/{name}.json",
    "description": "A component for building onboarding tours. Designed to integrate with shadcn/ui.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@tuiparts",
    "homepage": "https://tuiparts.sh",
    "url": "https://tuiparts.sh/r/{name}.json",
    "description": "OpenTUI recipes, made simple. Ready to use, customizable terminal UI recipes for Core, React, and Solid.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@turbopills-ui",
    "homepage": "https://www.turbopills.com/ui/docs",
    "url": "https://ui.turbopills.com/r/{name}.json",
    "description": "Beautiful, accessible, and customizable React components for your telehealth applications.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@typedora-ui",
    "homepage": "https://typedora-ui.netlify.app",
    "url": "https://typedora-ui.netlify.app/r/{name}.json",
    "description": "Typedora UI is a next-generation extension layer for shadcn/ui, designed to bring full type-safety to your UI components.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@uicapsule",
    "homepage": "https://uicapsule.com",
    "url": "https://uicapsule.com/r/{name}.json",
    "description": "A curated collection of components that spark joy. Featuring interactive concepts, design experiments, and components in the intersection of AI/UI.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@uselayouts",
    "homepage": "https://uselayouts.com",
    "url": "https://uselayouts.com/r/{name}.json",
    "description": "A collection of premium animated React components and micro-interactions built with Motion for building fluid, professional interfaces.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@utilcn",
    "homepage": "https://utilcn.dev",
    "url": "https://utilcn.dev/r/{name}.json",
    "description": "Fullstack registry items to start those big features. Utilcn has ChatGPT Apps, file uploading (with progress bars) and downloading, and a way to make your env vars typesafe on the backend.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@velobits",
    "homepage": "https://ui.velobits.dev",
    "url": "https://ui.velobits.dev/r/{name}.json",
    "description": "An open source collection of accessible, contrast-gated React components on a warm neutral palette and a two-tier glass material — the VeloBits design system, authored once and shipped both as an npm package and as this registry.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@wa-ui",
    "homepage": "https://ui.meta-cloud-api.site",
    "url": "https://ui.meta-cloud-api.site/r/{name}.json",
    "description": "Production-ready WhatsApp Web UI components built on WDS design tokens with Tailwind CSS v4 and @base-ui/react.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@washiveil",
    "homepage": "https://washiveil.alexchih.com",
    "url": "https://washiveil.alexchih.com/r/{name}.json",
    "description": "Washi at the ground, veils above, three lights beneath. A design system with Chinese & Japanese typography considered from the start.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@waves-cn",
    "homepage": "https://waves-cn.vercel.app",
    "url": "https://waves-cn.vercel.app/r/{name}.json",
    "description": "A collection of wave players and waveform components built with wavesurfer.js and shadcn/ui.",
    "status": "healthy",
    "score": 97,
    "availability30d": 99.3
  },
  {
    "namespace": "@animate-ui",
    "homepage": "https://animate-ui.com",
    "url": "https://animate-ui.com/r/{name}.json",
    "description": "A fully animated, open-source React component distribution. Browse a list of animated primitives, components and icons you can install and use in your projects.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@canvas-ui",
    "homepage": "https://canvasui.dev/",
    "url": "https://canvasui.dev/r/{name}.json",
    "description": "Creative html-in-canvas components. React, Vue, Svelte, TS.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@cnippet",
    "homepage": "https://ui.cnippet.dev/",
    "url": "https://ui.cnippet.dev/r/{name}.json",
    "description": "Cnippet UI is a production-ready, curated set of accessible and composable React components—built with Base UI and Tailwind CSS. Copy, paste, and ship stunning interfaces faster.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@coss",
    "homepage": "https://coss.com/ui",
    "url": "https://coss.com/ui/r/{name}.json",
    "description": "A new, modern UI component library built on top of Base UI. Built for developers and AI.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@diceui",
    "homepage": "https://www.diceui.com/",
    "url": "https://diceui.com/r/{style}/{name}.json",
    "description": "Accessible shadcn/ui components built with React, TypeScript, and Tailwind CSS. Copy-paste ready, and customizable.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@kanpeki",
    "homepage": "https://kanpeki.vercel.app",
    "url": "https://kanpeki.vercel.app/r/{name}.json",
    "description": "A set of perfect-designed components built on top of React Aria and Motion.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@rescript-shadcn",
    "homepage": "https://rescript-shadcn.miriad.studio",
    "url": "https://rescript-shadcn.miriad.studio/r/{name}.json",
    "description": "Shadcn components rewritten in Rescript, compatible with shadcn CLI.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcnui-blocks",
    "homepage": "https://shadcnui-blocks.com",
    "url": "https://shadcnui-blocks.com/r/{name}.json",
    "description": "A collection of premium, production-ready shadcn/ui blocks, components and templates.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@svgl",
    "homepage": "https://svgl.app",
    "url": "https://svgl.app/r/{name}.json",
    "description": "A beautiful library with SVG logos.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@taki",
    "homepage": "https://taki-ui.com",
    "url": "https://taki-ui.com/r/{name}.json",
    "description": "Beautifully designed, accessible components that you can copy and paste into your apps. Made with React Aria Components and Shadcn tokens.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@termcn",
    "homepage": "https://termcn.vercel.app",
    "url": "https://termcn.vercel.app/r/{name}.json",
    "description": "Beautiful terminal UIs, made simple. Ready to use, customizable terminal UI components for React.",
    "status": "healthy",
    "score": 96,
    "availability30d": 99.3
  },
  {
    "namespace": "@bklit",
    "homepage": "https://ui.bklit.com",
    "url": "https://ui.bklit.com/r/{name}.json",
    "description": "Open-source composable chart components for React — line, area, bar, pie, radar, maps, and more. Built with Visx, Motion, and shadcn/ui.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@ericts",
    "homepage": "https://ui.ericts.com",
    "url": "https://ui.ericts.com/r/{name}.json",
    "description": "Motion-focused shadcn-compatible components, hooks, and blocks for polished React interfaces.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@glass-ui",
    "homepage": "https://glass-ui.crenspire.com",
    "url": "https://glass-ui.crenspire.com/r/{name}.json",
    "description": "A shadcn-ui compatible registry distributing 40+ glassmorphic React/TypeScript components with Apple-inspired design. Components include enhanced visual effects (glow, shimmer, ripple), theme support, and customizable glassmorphism styling.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@jolyui",
    "homepage": "https://www.jolyui.dev",
    "url": "https://www.jolyui.dev/r/{name}.json",
    "description": "JolyUI is a modern React component library built with TypeScript and Tailwind CSS.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@kibo-ui",
    "homepage": "https://www.kibo-ui.com/",
    "url": "https://www.kibo-ui.com/r/{name}.json",
    "description": "Kibo UI is a custom registry of composable, accessible and open source components designed for use with shadcn/ui.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@kokonutui",
    "homepage": "https://kokonutui.com",
    "url": "https://kokonutui.com/r/{name}.json",
    "description": "Collection of stunning components built with Tailwind CSS, shadcn/ui and Motion to use on your websites.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@limeplay",
    "homepage": "https://limeplay.winoffrg.dev",
    "url": "https://limeplay.winoffrg.dev/r/{name}.json",
    "description": "Modern UI Library for building media players in React. Powered by Shaka Player.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@manifest",
    "homepage": "https://ui.manifest.build",
    "url": "https://ui.manifest.build/r/{name}.json",
    "description": "Agentic UI toolkit for building MCP Apps. Open-source components and blocks ready to use within your chat app.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@mui-treasury",
    "homepage": "https://www.mui-treasury.com",
    "url": "https://mui-treasury.com/r/{name}.json",
    "description": "A collection of hand-crafted interfaces built on top of MUI components",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@navui",
    "homepage": "https://ui.navdeepsingh.dev",
    "url": "https://ui.navdeepsingh.dev/r/{name}.json",
    "description": "shadcn-compatible components, blocks, and illustrations that adapt to your existing design configuration.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@quiz-ui",
    "homepage": "https://quiz-ui-phi.vercel.app",
    "url": "https://quiz-ui-phi.vercel.app/r/{name}.json",
    "description": "Headless, Radix-based components for building quiz funnels — shadcn-style distribution, style entirely via className.",
    "status": "healthy",
    "score": 95,
    "availability30d": 98.1
  },
  {
    "namespace": "@retab",
    "homepage": "https://ui.retab.com",
    "url": "https://ui.retab.com/r/{name}.json",
    "description": "Document-processing UI components for Retab — file, OCR, and data viewers, schema builders, dropzones, and extraction blocks, built on shadcn/ui.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@retroui",
    "homepage": "https://retroui.dev",
    "url": "https://retroui.dev/r/{name}.json",
    "description": "A Neobrutalism styled React + TailwindCSS UI library for building bold, modern web apps. Perfect for any project using Shadcn/ui.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@roiui",
    "homepage": "https://roiui.com",
    "url": "https://roiui.com/r/{name}.json",
    "description": "Roi UI is a library that offers UI components and blocks built with Base UI primitives. Some blocks and components use motion (framer). Everything is open-source and will be forever.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@scrimui",
    "homepage": "https://scrimui.dev",
    "url": "https://scrimui.dev/r/{name}.json",
    "description": "Free, open-source React components and patterns for AI interfaces, including prompts, streaming messages, reasoning, tool calls, citations, agents, memory, voice, and safety.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.1
  },
  {
    "namespace": "@shadcnhooks",
    "homepage": "https://shadcn-hooks.com",
    "url": "https://shadcn-hooks.com/r/{name}.json",
    "description": "A comprehensive React Hooks Collection built with Shadcn.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@smoothui",
    "homepage": "https://smoothui.dev",
    "url": "https://smoothui.dev/r/{name}.json",
    "description": "A collection of beautifully crafted motion components built with React, Framer Motion, and TailwindCSS. Designed to elevate microinteractions, each component focuses on smooth animations, subtle feedback, and delightful UX. Perfect for designers and developers who want to add refined motion to their interfaces — copy, paste, and make your UI come alive.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@soralabs",
    "homepage": "https://ui.soralabs.studio",
    "url": "https://ui.soralabs.studio/r/{name}.json",
    "description": "Motion-first React primitives and animated UI components for shadcn/ui. Copy, customize, and ship fluid interfaces.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@spell",
    "homepage": "https://spell.sh",
    "url": "https://spell.sh/r/{name}.json",
    "description": "Beautiful, sophisticated UI components designed for modern React and Tailwind CSS applications.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@supabase",
    "homepage": "https://supabase.com/ui",
    "url": "https://supabase.com/ui/r/{name}.json",
    "description": "A collection of React components and blocks built on the shadcn/ui library that connect your front-end to your Supabase back-end via a single command.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99
  },
  {
    "namespace": "@tailwind-admin",
    "homepage": "https://tailwind-admin.com/",
    "url": "https://tailwind-admin.com/r/{name}.json",
    "description": "Tailwind Builder provides free tailwind admin dashboard templates, components and ui-blocks built with React, Next.js, Tailwind CSS, and shadcn/ui to help you build admin panels quickly and efficiently.",
    "status": "healthy",
    "score": 95,
    "availability30d": 99.3
  },
  {
    "namespace": "@amplo",
    "homepage": "https://amplo.ale.design",
    "url": "https://amplo.ale.design/r/{name}.json",
    "description": "OKLCH-native, Display-P3-aware composable fill picker with WCAG/APCA contrast metrics, gamut detection, and full keyboard accessibility.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@asanshay",
    "homepage": "https://ds.asanshay.com",
    "url": "https://ds.asanshay.com/r/{name}.json",
    "description": "Clean, beautiful, and simple UI primitives and AI elements.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@auth0",
    "homepage": "https://auth0.com",
    "url": "https://ui.auth0.com/r/{name}.json",
    "description": "Official Auth0 Universal Components for Web. Accelerate development with pre-built, embeddable UI for enterprise SSO, MFA, and organization management",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@baraile-loader",
    "homepage": "https://shadcn-braille-loader.vercel.app",
    "url": "https://shadcn-braille-loader.vercel.app/r/{name}.json",
    "description": "A simple braille-inspired loader components for shadcn/ui.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@cognicatch",
    "homepage": "https://cognicatch.dev",
    "url": "https://cognicatch.dev/registry/{name}.json",
    "description": "Adaptive Error Boundaries and graceful fallback UIs (Banners, Modals, Toasts).",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@delego",
    "homepage": "https://github.com/Delego-Dev/registry",
    "url": "https://raw.githubusercontent.com/Delego-Dev/registry/main/public/r/{name}.json",
    "description": "Design-system registry for Delego — intent-bound action authorization for AI agents. Theme (OKLCH) plus signature components: decision pill, signed receipt, status badge, field.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@dominik-ui",
    "homepage": "https://dominikkoch.dev/ui",
    "url": "https://dominikkoch.dev/r/{name}.json",
    "description": "Opinionated components and tools for building modern AI interfaces.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@dsikeres1",
    "homepage": "https://dsikeres1.github.io/react-date-range-picker/",
    "url": "https://dsikeres1.github.io/react-date-range-picker/r/{name}.json",
    "description": "A headless, composable date & date range picker for React. 5 picker types, 15 locales, dark mode, accessible. Zero dependencies.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@grootstudio",
    "homepage": "https://grootstudio.vercel.app",
    "url": "https://grootstudio.vercel.app/r/{name}.json",
    "description": "A premium, open source component registry for SEO-friendly, high-performance React applications",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@kaui",
    "homepage": "https://kaui-shadcn-registry.vercel.app",
    "url": "https://kaui-shadcn-registry.vercel.app/r/{name}.json",
    "description": "Personal well crafted components for Shadcn ui",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@knock-codes",
    "homepage": "https://knock.codes",
    "url": "https://knock.codes/r/react/{name}.json",
    "description": "Copy-paste, session-gated access blocks for React — PIN/Knock Code unlock screens, protected routes/layouts/modals, a headless useKnockCodes hook, and full-page templates.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@lens-blocks",
    "homepage": "https://lensblocks.com",
    "url": "https://lensblocks.com/r/{name}.json",
    "description": "A collection of social media components for use with Lens Social Protocol.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@nordaun",
    "homepage": "https://ui.nordaun.com",
    "url": "https://ui.nordaun.com/r/{name}.json",
    "description": "Simple components for your extraordinary creations.",
    "status": "healthy",
    "score": 94,
    "availability30d": 98.8
  },
  {
    "namespace": "@pixelact-ui",
    "homepage": "https://pixelactui.com",
    "url": "https://pixelactui.com/r/{name}.json",
    "description": "Playful pixel art style components library built on top of shadcn. Perfect for retro style projects and games.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@reui",
    "homepage": "https://reui.io",
    "url": "https://reui.io/r/{style}/{name}.json",
    "description": "Free & open-source library of 1,000+ components and patterns to 10x your productivity in shadcn projects.",
    "status": "healthy",
    "score": 94,
    "availability30d": 77.9
  },
  {
    "namespace": "@satoriui",
    "homepage": "https://satoriui.site",
    "url": "https://satoriui.site/r/{name}.json",
    "description": "A comprehensive suite of high-fidelity interaction components. It offers motion-driven components that designed with motion-react and tailwindcss, that blends seamlessly.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@scrollxui",
    "homepage": "https://www.scrollxui.dev",
    "url": "https://www.scrollxui.dev/registry/{name}.json",
    "description": "ScrollX UI is an open-source React and shadcn-compatible component library for animated, interactive, and customizable user interfaces. It offers motion-driven components that blend seamlessly with modern ShadCN setups.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcn-editor",
    "homepage": "https://shadcn-editor.vercel.app",
    "url": "https://raw.githubusercontent.com/htmujahid/shadcn-editor/refs/heads/main/public/r/{name}.json",
    "description": "Accessible, Customizable, Rich Text Editor. Made with Lexical and Shadcn/UI. Open Source. Open Code.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@text-ui",
    "homepage": "https://joelachance.github.io/text-ui/docs",
    "url": "https://joelachance.github.io/text-ui/r/{name}.json",
    "description": "A shadcn/ui registry with EchoText (`echo-text`): layered stroke text that follows the pointer—minimal setup, drop-in component.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@trophy-ui",
    "homepage": "https://ui.trophy.so",
    "url": "https://ui.trophy.so/r/{name}.json",
    "description": "Open-source gamification UI components for streaks, achievements, leaderboards, points, and more. Built on shadcn/ui and Tailwind CSS.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@wds",
    "homepage": "https://wds-shadcn-registry.netlify.app/",
    "url": "https://wds-shadcn-registry.netlify.app/r/{name}.json",
    "description": "A collection of accessible components built for use with Shadcn.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@zippystarter",
    "homepage": "https://zippystarter.com",
    "url": "https://zippystarter.com/r/{name}.json",
    "description": "Expertly crafted blocks, components & themes for shadcn/ui.",
    "status": "healthy",
    "score": 94,
    "availability30d": 99.3
  },
  {
    "namespace": "@billingsdk",
    "homepage": "https://billingsdk.com",
    "url": "https://billingsdk.com/r/{name}.json",
    "description": "BillingSDK is an open-source React and Next.js component library for SaaS billing and payments. It offers ready-to-use, customizable components for subscriptions, invoices, usage-based pricing and billing - fully compatible with Dodo Payments and Stripe.",
    "status": "healthy",
    "score": 93,
    "availability30d": 99.3
  },
  {
    "namespace": "@blocks-so",
    "homepage": "https://blocks.so",
    "url": "https://blocks.so/r/{name}.json",
    "description": "A set of clean, modern application building blocks for you in your applications. Free and Open Source",
    "status": "healthy",
    "score": 93,
    "availability30d": 99.3
  },
  {
    "namespace": "@oidc",
    "homepage": "https://ui.shadcn.com/oidc",
    "url": "https://ui.shadcn.com/oidc/r/{name}.json",
    "description": "A component registry for OIDC policy forms. Pick identity providers, a form library, and a validation library, preview in the builder, then copy the code into your app.",
    "status": "healthy",
    "score": 93,
    "availability30d": 97.3
  },
  {
    "namespace": "@shoogle",
    "homepage": "https://shoogle.dev",
    "url": "https://shoogle.dev/r/{name}.json",
    "description": "Search shadcn blocks and components across community registries from the CLI",
    "status": "healthy",
    "score": 93,
    "availability30d": 99.3
  },
  {
    "namespace": "@systaliko-ui",
    "homepage": "https://systaliko-ui.vercel.app",
    "url": "https://systaliko-ui.vercel.app/r/{name}.json",
    "description": "UI component library, Designed for flexibility, built for customization, and crafted to scale across variants and use cases.",
    "status": "healthy",
    "score": 93,
    "availability30d": 99.3
  },
  {
    "namespace": "@vernostudio",
    "homepage": "https://verno-studio.vercel.app/components",
    "url": "https://verno-studio.vercel.app/r/{name}.json",
    "description": "The full OKLCH scale plus every variable shadcn components read, so anything you install lands on the same tokens instead of its own colors.",
    "status": "healthy",
    "score": 93,
    "availability30d": 99.3
  },
  {
    "namespace": "@atelier",
    "homepage": "https://www.atelier-ui.com",
    "url": "https://www.atelier-ui.com/r/{name}.json",
    "description": "A WebGL and Motion system for React that runs many effects on one shared canvas. Shader, cursor, scroll and text effects, 3D galleries, plus page transitions for Next.js. Built with Three.js, React Three Fiber, Motion, and Lenis smooth scroll.",
    "status": "degraded",
    "score": 92,
    "availability30d": 99.3
  },
  {
    "namespace": "@designali",
    "homepage": "https://designali.com",
    "url": "https://designali.com/r/{name}.json",
    "description": "Where thoughtful design meets production-ready code. I design and build digital experiences that look great, feel intuitive, and work beautifully.",
    "status": "healthy",
    "score": 92,
    "availability30d": 98.1
  },
  {
    "namespace": "@exabase",
    "homepage": "https://exawizards.com/exabase/design/",
    "url": "https://exawizards.com/exabase/design/registry/{name}.json",
    "description": "A collection of UI components based on the exaBase Design System, built with React and Tailwind CSS.",
    "status": "healthy",
    "score": 92,
    "availability30d": 91.1
  },
  {
    "namespace": "@fluid",
    "homepage": "https://www.fluidfunctionalism.com",
    "url": "https://www.fluidfunctionalism.com/r/{name}.json",
    "description": "Fluid components used exclusively in service of functional clarity. Proximity hover, spring animations, font-weight transitions, and animated focus rings.",
    "status": "degraded",
    "score": 92,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcn-studio",
    "homepage": "https://shadcnstudio.com",
    "url": "https://shadcnstudio.com/r/{style}/{name}.json",
    "description": "An open-source set of shadcn/ui components, blocks, and templates with a powerful theme generator.",
    "status": "healthy",
    "score": 92,
    "availability30d": 77.9
  },
  {
    "namespace": "@iconiq",
    "homepage": "https://iconiqui.com",
    "url": "https://iconiqui.com/r/{name}.json",
    "description": "Iconiq is a collection of icons designed for web applications. It is a modern, clean, and minimalistic icon set that is perfect for web applications.",
    "status": "healthy",
    "score": 91,
    "availability30d": 99.3
  },
  {
    "namespace": "@aceternity",
    "homepage": "https://ui.aceternity.com",
    "url": "https://ui.aceternity.com/registry/{name}.json",
    "description": "A modern component library built with Tailwind CSS and Motion for React, Aceternity UI contains unique and interactive components that can make your landing pages look 100x better.",
    "status": "degraded",
    "score": 90,
    "availability30d": 99.3
  },
  {
    "namespace": "@paceui-gsap",
    "homepage": "https://gsap.paceui.com",
    "url": "https://gsap.paceui.com/r/{name}.json",
    "description": "Animated GSAP components crafted for smooth interaction and rich detail.",
    "status": "healthy",
    "score": 90,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcn-dashboard",
    "homepage": "https://shadcndashboard.dev",
    "url": "https://shadcndashboard.dev/r/{name}.json",
    "description": "Shadcn Dashboard is a collection of modern, production-ready dashboard layouts, components, and UI patterns built on top of shadcn/ui and Tailwind CSS. It’s designed to help developers build clean, scalable, and data-driven dashboards faster—without compromising on performance, accessibility, or customization.",
    "status": "degraded",
    "score": 90,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcn-map",
    "homepage": "https://shadcn-map.vercel.app",
    "url": "http://shadcn-map.vercel.app/r/{name}.json",
    "description": "A map component for shadcn/ui. Built with Leaflet and React Leaflet.",
    "status": "healthy",
    "score": 88,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcnstore",
    "homepage": "https://www.shadcnstore.com",
    "url": "https://shadcnstore.com/r/{name}.json",
    "description": "A growing collection of shadcn/ui components, blocks, and templates for building modern web apps.",
    "status": "degraded",
    "score": 88,
    "availability30d": 99.3
  },
  {
    "namespace": "@abui",
    "homepage": "https://abui.io",
    "url": "https://abui.io/r/{name}.json",
    "description": "A shadcn-compatible registry of reusable components, blocks, and utilities conforming to Vercel's components.build specification",
    "status": "degraded",
    "score": 87,
    "availability30d": 99.3
  },
  {
    "namespace": "@efferd",
    "homepage": "https://efferd.com/",
    "url": "https://efferd.com/r/{name}.json",
    "description": "A collection of beautifully crafted Shadcn/UI blocks, designed to help developers build modern websites with ease.",
    "status": "degraded",
    "score": 87,
    "availability30d": 99.3
  },
  {
    "namespace": "@hexui",
    "homepage": "https://hexui.sh",
    "url": "https://hexui.sh/r/{name}.json",
    "description": "A shadcn/ui registry of high-quality React blocks and templates.",
    "status": "healthy",
    "score": 87,
    "availability30d": 86.6
  },
  {
    "namespace": "@lumiui",
    "homepage": "https://www.lumiui.dev",
    "url": "https://www.lumiui.dev/r/{name}.json",
    "description": "Composable React components powered by Base UI and Tailwind CSS — Build fast, customize everything.",
    "status": "degraded",
    "score": 87,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcn-space",
    "homepage": "https://shadcnspace.com",
    "url": "https://shadcnspace.com/r/{name}.json",
    "description": "ShadcnSpace is a collection of extra-ordinary, highly customizable shadcn/ui components, blocks, and themes to build modern UIs with speed and clarity.",
    "status": "degraded",
    "score": 87,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcncraft",
    "homepage": "https://shadcncraft.com",
    "url": "https://shadcncraft.com/r/{name}.json",
    "description": "A starter collection of polished shadcn/ui components and blocks built to production standards. Part of a larger Figma + React system designed to scale with your product.",
    "status": "degraded",
    "score": 87,
    "availability30d": 99.3
  },
  {
    "namespace": "@unlumen-ui",
    "homepage": "https://ui.unlumen.com",
    "url": "https://ui.unlumen.com/r/{name}.json",
    "description": "Primitives and components with serious attention to animation and design. Copy, own, ship.",
    "status": "degraded",
    "score": 87,
    "availability30d": 99.3
  },
  {
    "namespace": "@agentcn",
    "homepage": "https://agentcn.vercel.app",
    "url": "https://agentcn.vercel.app/r/{name}.json",
    "description": "Production-ready agents, made simple. Ready to use, customizable AI agent recipes. Built on Eve and Flue.",
    "status": "degraded",
    "score": 85,
    "availability30d": 99.3
  },
  {
    "namespace": "@cult-ui",
    "homepage": "https://www.cult-ui.com",
    "url": "https://cult-ui.com/r/{name}.json",
    "description": "Cult UI is a rare, curated set of shadcn-compatible, headless and composable components—tastefully animated with Framer Motion.",
    "status": "observing",
    "score": 85,
    "availability30d": 88.3
  },
  {
    "namespace": "@elevenlabs-ui",
    "homepage": "https://ui.elevenlabs.io",
    "url": "https://ui.elevenlabs.io/r/{name}.json",
    "description": "A collection of Open Source agent and audio components that you can customize and extend.",
    "status": "observing",
    "score": 85,
    "availability30d": 88.3
  },
  {
    "namespace": "@motion-primitives",
    "homepage": "https://www.motion-primitives.com",
    "url": "https://motion-primitives.com/c/{name}.json",
    "description": "Beautifully designed motions components. Easy copy-paste. Customizable. Open Source. Built for engineers and designers.",
    "status": "observing",
    "score": 85,
    "availability30d": 88.3
  },
  {
    "namespace": "@phucbm",
    "homepage": "https://phucbm.com/components",
    "url": "https://phucbm.com/r/{name}.json",
    "description": "A collection of modern React UI components with GSAP animations.",
    "status": "observing",
    "score": 85,
    "availability30d": 88.3
  },
  {
    "namespace": "@tailark",
    "homepage": "https://tailark.com",
    "url": "https://tailark.com/r/{name}.json",
    "description": "Shadcn blocks designed for building modern marketing websites.",
    "status": "degraded",
    "score": 85,
    "availability30d": 99.3
  },
  {
    "namespace": "@blockus",
    "homepage": "https://blockus.lndevui.com",
    "url": "https://blockus.lndevui.com/r/{name}.json",
    "description": "Production-ready React blocks built on shadcn/ui and Tailwind — drop them in, swap the copy, ship the page. Heroes, pricing and footer sections crafted by hand.",
    "status": "degraded",
    "score": 82,
    "availability30d": 99.3
  },
  {
    "namespace": "@initium",
    "homepage": "https://initium.sh",
    "url": "https://app.initium.sh/r/styles/{style}/{name}.json",
    "description": "Conversion-focused marketing blocks and landing page sections for shadcn/ui, with a visual style editor, agent skills, and the first block of every category free to install.",
    "status": "degraded",
    "score": 82,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcnuikit",
    "homepage": "https://shadcnuikit.com",
    "url": "https://shadcnuikit.com/r/{name}.json",
    "description": "Launch your projects faster with admin dashboards, website templates, components, blocks, and pre-built real-world examples.",
    "status": "degraded",
    "score": 82,
    "availability30d": 99.3
  },
  {
    "namespace": "@blockforge",
    "homepage": "https://blockforge.terravidhal.me",
    "url": "https://blockforge.terravidhal.me/r/{name}.json",
    "description": "170+ production-grade shadcn/ui blocks, forged to ship. Full source in TypeScript + Tailwind CSS, plus a page builder and starter pages. Copy, paste, ship.",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@heatmap",
    "homepage": "https://shadcn-heatmap.pages.dev",
    "url": "https://shadcn-heatmap.pages.dev/r/{name}.json",
    "description": "Beautiful, accessible heatmap components for React: GitHub-style calendar, weekday x hour matrix, date x hour, and status timeline. Built with shadcn/ui conventions.",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@launchui",
    "homepage": "https://www.launchuicomponents.com/",
    "url": "https://www.launchuicomponents.com/r/{name}.json",
    "description": "Carefully crafted landing page components and templates built with React, Shadcn/ui and Tailwind.",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@nexus-labs",
    "homepage": "https://nexus-ui.com",
    "url": "https://nexus-ui.com/r/{name}.json",
    "description": "Motion-native animated components for Next.js — backgrounds, heroes, inputs, carousels, and more. Open source. Copy-ready TypeScript.",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@paceui",
    "homepage": "https://paceui.com",
    "url": "https://paceui.com/r/{name}.json",
    "description": "Carefully built UI blocks for real apps and dashboards, designed to integrate smoothly from early ideas to production releases.",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@uitripled",
    "homepage": "https://ui.tripled.work",
    "url": "https://ui.tripled.work/r/{name}.json",
    "description": "An open-source, Production-ready UI components and blocks powered by shadcn/ui and Framer Motion",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@uui",
    "homepage": "https://uui.app",
    "url": "https://uui.app/r/{name}.json",
    "description": "Inspiration for UI Interfaces. Discover UI ideas, micro-interactions, and components drawn from real products.",
    "status": "degraded",
    "score": 81,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcnblocks",
    "homepage": "https://shadcnblocks.com",
    "url": "https://shadcnblocks.com/r/{name}.json",
    "description": "A shadcn/ui registry with 1429 blocks, 1189 component variants, 14 templates, themes, and admin dashboard patterns.",
    "status": "degraded",
    "score": 80,
    "availability30d": 99.3
  },
  {
    "namespace": "@amicro",
    "homepage": "https://amicro.vercel.app",
    "url": "https://amicro.vercel.app/r/{name}.json",
    "description": "Open-source React micro-interactions and UI component registry powered by Motion.",
    "status": "degraded",
    "score": 79,
    "availability30d": 99.3
  },
  {
    "namespace": "@wensity",
    "homepage": "https://ui.wensity.com/components",
    "url": "https://raw.githubusercontent.com/wensity/registry/main/{name}.json",
    "description": "React and Next.js UI primitives, components, and motion, themeable end to end from one design token contract. Built on Base UI and Tailwind CSS v4. Free Wensity components.",
    "status": "degraded",
    "score": 79,
    "availability30d": 99.3
  },
  {
    "namespace": "@pacekit",
    "homepage": "https://ui.pacekit.dev",
    "url": "https://ui.pacekit.dev/r/{name}.json",
    "description": "Carefully built UI blocks for real apps and dashboards, designed to integrate smoothly from early ideas to production releases.",
    "status": "degraded",
    "score": 78,
    "availability30d": 99.3
  },
  {
    "namespace": "@beste-ui",
    "homepage": "https://ui.beste.co",
    "url": "https://ui.beste.co/r/{name}.json",
    "description": "Production-ready UI blocks for landing pages, dashboards, and web apps.",
    "status": "degraded",
    "score": 77,
    "availability30d": 99.3
  },
  {
    "namespace": "@shadcn-ui-blocks",
    "homepage": "https://www.shadcn-ui-blocks.com",
    "url": "https://www.shadcn-ui-blocks.com/r/{name}.json",
    "description": "Shadcn blocks across standard collections and handcrafted premium collections, plus a beautiful templates. Start free, then unlock more with Pro.",
    "status": "degraded",
    "score": 77,
    "availability30d": 99.3
  },
  {
    "namespace": "@tailgrids",
    "homepage": "https://tailgrids.com",
    "url": "https://tailgrids.com/docs/r/{name}.json",
    "description": "React UI Components, Powered by Tailwind CSS",
    "status": "degraded",
    "score": 77,
    "availability30d": 99.3
  },
  {
    "namespace": "@mozaika",
    "homepage": "https://mozaika.design",
    "url": "https://mozaika.design/r/{name}.json",
    "description": "Design systems measured from real product UIs — color roles, typography and spacing as themes installable with the shadcn CLI. Free open shelf; companion MCP server for AI coding agents.",
    "status": "degraded",
    "score": 76,
    "availability30d": 99.3
  },
  {
    "namespace": "@paykit-sdk",
    "homepage": "https://www.usepaykit.dev",
    "url": "https://www.usepaykit.dev/r/{name}.json",
    "description": "Unified payments SDK for builders — handle checkout, billing, and webhooks across Stripe, PayPal, Adyen, and regional gateways with a single integration.",
    "status": "degraded",
    "score": 76,
    "availability30d": 99.3
  },
  {
    "namespace": "@extend",
    "homepage": "https://ui.extend.ai",
    "url": "https://ui.extend.ai/r/{name}.json",
    "description": "A collection of UI components for building document agents and human-in-the-loop review workflows.",
    "status": "unavailable",
    "score": 64,
    "availability30d": 59.4
  }
]
